/* Generated by re2c 1.0.3 on Tue Aug 14 21:22:00 2018 */
#line 1 "../re2c/lexer.re"
#include "lexer.h"

#include <cstdint>

#include <stack>

namespace{
  
  constexpr uint64_t utf8Mask_(int bytes){
    if(bytes >= 2){
      int mask1 = 0x8000, mask2 = 0x80;
      for(; bytes > 2; --bytes){
        mask1 = (mask1 << 8) | (mask1 << 7);
        mask2 = (mask2 << 8) | 0x80;
      }
      return mask1 | mask2;
    }else return 0;
  }
  
  template<int bytes>
  inline uint64_t splitUtf8CodePoint_(uint64_t code_point){
    uint64_t mask = 0x3f;
    for(int i = 1; i < bytes; ++i){
      code_point = (code_point & mask) | ((code_point & ~mask) << 2);
      mask = (mask << 8) | 0xff;
    }
    return code_point;
  }
  
  template<int chars>
  inline void enterUtf8CodePoint_(std::string* dest, const char* code){
    uint64_t code_point;
    code -= chars;
    for(int i = 0; i < chars; ++i){
      code_point <<= 8;
      if(isdigit(*code)){
        code_point |= (*code) - '0';
      }else{
        code_point |= (*code | 0x20) - 'a' + 10;
      }
      ++code;
    }
    if(code_point < 0x80){
      dest->push_back((char)code_point);
      return;
    }else{
      int bytes = 2;
      for(uint64_t cp = code_point >> 11; cp > 0; ++bytes, cp >> 5);
      
      switch(bytes){
      case 2:
        code_point = splitUtf8CodePoint_<2>(code_point) | utf8Mask_(2);
        goto write_2_bytes;
      case 3:
        code_point = splitUtf8CodePoint_<3>(code_point) | utf8Mask_(3);
        goto write_3_bytes;
      case 4:
        code_point = splitUtf8CodePoint_<4>(code_point) | utf8Mask_(4);
        goto write_4_bytes;
      case 5:
        code_point = splitUtf8CodePoint_<5>(code_point) | utf8Mask_(5);
        goto write_5_bytes;
      case 6:
        code_point = splitUtf8CodePoint_<6>(code_point) | utf8Mask_(6);
        goto write_6_bytes;
      case 7:
        code_point = splitUtf8CodePoint_<7>(code_point) | utf8Mask_(7);
        goto write_7_bytes;
      }
      
    write_7_bytes:
      dest->push_back(code[-7]);
    write_6_bytes:
      dest->push_back(code[-6]);
    write_5_bytes:
      dest->push_back(code[-5]);
    write_4_bytes:
      dest->push_back(code[-4]);
    write_3_bytes:
      dest->push_back(code[-3]);
    write_2_bytes:
      dest->push_back(code[-2]);
      dest->push_back(code[-1]);
    }
  }
}

Lexer::Lexer(const char* mem){
  this->mem_ = mem;
}

std::vector<Lexeme> Lexer::lex(std::vector<std::unique_ptr<char[]>>* errors){
  const char* marker;
  const char* token;
  
  const char* reader = this->mem_;
  int counter = 0;
  
  #define YYDEBUG(state, current)
  
  std::vector<Lexeme> lexemes;
  std::stack<char> br_stack;
  br_stack.push('#');
  
  uint16_t line = 1;
  const char* line_start = reader;
  
  #define PLACE_LEXEME(params) \
    lexemes.emplace_back(params, std::make_pair(line, token - line_start));
  #define PUT_LEXEME(params) \
    lexemes.emplace_back(params, std::make_pair(line, token - line_start)); \
    continue;
  
  lexemes.emplace_back(LexemeType::Semicolon, std::make_pair(0, 0));
  
  for(;;){
    token = reader;
    
    #line 125 "../re2c/lexer.re"

    
    
#line 126 "../src/lexer.cpp"
{
	char yych;
	unsigned int yyaccept = 0;
	YYDEBUG(0, *reader);
	yych = *reader;
	switch (yych) {
	case 0x00:	goto yy2;
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case '#':
	case '$':
	case '&':
	case '\'':
	case ':':
	case '?':
	case '@':
	case '\\':
	case '^':
	case '`':
	case '|':
	case '~':
	case 0x7F:	goto yy4;
	case '\t':
	case '\v':
	case '\f':
	case '\r':
	case ' ':	goto yy6;
	case '\n':	goto yy8;
	case '!':	goto yy10;
	case '"':	goto yy11;
	case '%':	goto yy13;
	case '(':	goto yy15;
	case ')':	goto yy17;
	case '*':	goto yy19;
	case '+':	goto yy21;
	case ',':	goto yy23;
	case '-':	goto yy25;
	case '.':	goto yy27;
	case '/':	goto yy28;
	case '0':	goto yy30;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy32;
	case ';':	goto yy34;
	case '<':	goto yy36;
	case '=':	goto yy38;
	case '>':	goto yy40;
	case '[':	goto yy45;
	case ']':	goto yy47;
	case 'a':	goto yy49;
	case 'd':	goto yy50;
	case 'e':	goto yy51;
	case 'f':	goto yy52;
	case 'i':	goto yy53;
	case 'n':	goto yy54;
	case 'o':	goto yy55;
	case 'p':	goto yy56;
	case 't':	goto yy57;
	case 'v':	goto yy58;
	case 'w':	goto yy59;
	case '{':	goto yy60;
	case '}':	goto yy62;
	default:	goto yy42;
	}
yy2:
	YYDEBUG(2, *reader);
	++reader;
	YYDEBUG(3, *reader);
#line 128 "../re2c/lexer.re"
	{break;}
#line 227 "../src/lexer.cpp"
yy4:
	YYDEBUG(4, *reader);
	++reader;
yy5:
	YYDEBUG(5, *reader);
#line 130 "../re2c/lexer.re"
	{
        if(lexemes.back().type != LexemeType::Error){
          errors->emplace_back(dynSprintf("line %d: Invalid symbol.", line));
          PUT_LEXEME(LexemeType::Error);
        } else continue;
      }
#line 240 "../src/lexer.cpp"
yy6:
	YYDEBUG(6, *reader);
	++reader;
	YYDEBUG(7, *reader);
#line 138 "../re2c/lexer.re"
	{continue;}
#line 247 "../src/lexer.cpp"
yy8:
	YYDEBUG(8, *reader);
	++reader;
	YYDEBUG(9, *reader);
#line 140 "../re2c/lexer.re"
	{
        if((br_stack.top() == '{'
        || br_stack.top() == '#')
        && isStopLexeme(lexemes.back())){
          PLACE_LEXEME(LexemeType::Newline);
        }
        ++line;
        line_start = reader;
        continue;
      }
#line 263 "../src/lexer.cpp"
yy10:
	YYDEBUG(10, *reader);
	yych = *++reader;
	switch (yych) {
	case '=':	goto yy64;
	default:	goto yy5;
	}
yy11:
	YYDEBUG(11, *reader);
	++reader;
	YYDEBUG(12, *reader);
#line 172 "../re2c/lexer.re"
	{
        goto lex_string;
      }
#line 279 "../src/lexer.cpp"
yy13:
	YYDEBUG(13, *reader);
	yych = *++reader;
	switch (yych) {
	case '=':	goto yy66;
	default:	goto yy14;
	}
yy14:
	YYDEBUG(14, *reader);
#line 182 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Mod)}
#line 291 "../src/lexer.cpp"
yy15:
	YYDEBUG(15, *reader);
	++reader;
	YYDEBUG(16, *reader);
#line 202 "../re2c/lexer.re"
	{
        br_stack.push('(');
        PUT_LEXEME(LexemeType::LParen)
      }
#line 301 "../src/lexer.cpp"
yy17:
	YYDEBUG(17, *reader);
	++reader;
	YYDEBUG(18, *reader);
#line 214 "../re2c/lexer.re"
	{
        if(br_stack.top() == '('){
          br_stack.pop();
          PUT_LEXEME(LexemeType::RParen)
        }else{
          errors->emplace_back(dynSprintf("line %d: Unexpected ')'.", line));
          PUT_LEXEME(LexemeType::Error);
        }
      }
#line 316 "../src/lexer.cpp"
yy19:
	YYDEBUG(19, *reader);
	yych = *++reader;
	switch (yych) {
	case '=':	goto yy68;
	default:	goto yy20;
	}
yy20:
	YYDEBUG(20, *reader);
#line 180 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Mul)}
#line 328 "../src/lexer.cpp"
yy21:
	YYDEBUG(21, *reader);
	yych = *++reader;
	switch (yych) {
	case '+':	goto yy70;
	case '=':	goto yy72;
	default:	goto yy22;
	}
yy22:
	YYDEBUG(22, *reader);
#line 178 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Plus)}
#line 341 "../src/lexer.cpp"
yy23:
	YYDEBUG(23, *reader);
	++reader;
	YYDEBUG(24, *reader);
#line 198 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Comma)}
#line 348 "../src/lexer.cpp"
yy25:
	YYDEBUG(25, *reader);
	yych = *++reader;
	switch (yych) {
	case '=':	goto yy74;
	default:	goto yy26;
	}
yy26:
	YYDEBUG(26, *reader);
#line 179 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Minus)}
#line 360 "../src/lexer.cpp"
yy27:
	YYDEBUG(27, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy76;
	default:	goto yy5;
	}
yy28:
	YYDEBUG(28, *reader);
	yych = *++reader;
	switch (yych) {
	case '*':	goto yy79;
	case '/':	goto yy81;
	case '=':	goto yy84;
	default:	goto yy29;
	}
yy29:
	YYDEBUG(29, *reader);
#line 181 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Div)}
#line 390 "../src/lexer.cpp"
yy30:
	YYDEBUG(30, *reader);
	yyaccept = 0;
	yych = *(marker = ++reader);
	switch (yych) {
	case 'B':
	case 'b':	goto yy86;
	case 'O':
	case 'o':	goto yy89;
	case 'X':
	case 'x':	goto yy90;
	default:	goto yy33;
	}
yy31:
	YYDEBUG(31, *reader);
#line 156 "../re2c/lexer.re"
	{PUT_LEXEME(strtoull(token, nullptr, 10))}
#line 408 "../src/lexer.cpp"
yy32:
	YYDEBUG(32, *reader);
	yych = *++reader;
yy33:
	YYDEBUG(33, *reader);
	switch (yych) {
	case '.':	goto yy76;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy32;
	case 'E':
	case 'e':	goto yy88;
	default:	goto yy31;
	}
yy34:
	YYDEBUG(34, *reader);
	++reader;
	YYDEBUG(35, *reader);
#line 200 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Semicolon)}
#line 436 "../src/lexer.cpp"
yy36:
	YYDEBUG(36, *reader);
	yych = *++reader;
	switch (yych) {
	case '=':	goto yy91;
	default:	goto yy37;
	}
yy37:
	YYDEBUG(37, *reader);
#line 194 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Lt)}
#line 448 "../src/lexer.cpp"
yy38:
	YYDEBUG(38, *reader);
	yych = *++reader;
	switch (yych) {
	case '=':	goto yy93;
	default:	goto yy39;
	}
yy39:
	YYDEBUG(39, *reader);
#line 184 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Assign)}
#line 460 "../src/lexer.cpp"
yy40:
	YYDEBUG(40, *reader);
	yych = *++reader;
	switch (yych) {
	case '=':	goto yy95;
	default:	goto yy41;
	}
yy41:
	YYDEBUG(41, *reader);
#line 193 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Gt)}
#line 472 "../src/lexer.cpp"
yy42:
	YYDEBUG(42, *reader);
	yych = *++reader;
yy43:
	YYDEBUG(43, *reader);
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy44;
	default:	goto yy42;
	}
yy44:
	YYDEBUG(44, *reader);
#line 278 "../re2c/lexer.re"
	{
        StringView view(token, reader);
        String* str;
        auto it = this->string_table.find(view);
        if(it == this->string_table.end()){
          str = this->string_table.insert(
            std::make_pair(
              view,
              rc_ptr<String>(make_new<String>(view.first, view.second))
            )
          ).first->second.get();
        }else{
          str = it->second.get();
        }
        lexemes.emplace_back(
          LexemeType::Identifier,
          str,
          std::make_pair(line, token - line_start)
        );
        
        continue;
      }
#line 571 "../src/lexer.cpp"
yy45:
	YYDEBUG(45, *reader);
	++reader;
	YYDEBUG(46, *reader);
#line 210 "../re2c/lexer.re"
	{
        br_stack.push('[');
        PUT_LEXEME(LexemeType::LBracket)
      }
#line 581 "../src/lexer.cpp"
yy47:
	YYDEBUG(47, *reader);
	++reader;
	YYDEBUG(48, *reader);
#line 235 "../re2c/lexer.re"
	{
        if(br_stack.top() == '['){
          br_stack.pop();
          PUT_LEXEME(LexemeType::RBracket)
        }else{
          errors->emplace_back(dynSprintf("line %d: Unexpected ']'.", line));
          PUT_LEXEME(LexemeType::Error);
        }
      }
#line 596 "../src/lexer.cpp"
yy49:
	YYDEBUG(49, *reader);
	yych = *++reader;
	switch (yych) {
	case 'n':	goto yy97;
	case 's':	goto yy98;
	default:	goto yy43;
	}
yy50:
	YYDEBUG(50, *reader);
	yych = *++reader;
	switch (yych) {
	case 'o':	goto yy99;
	default:	goto yy43;
	}
yy51:
	YYDEBUG(51, *reader);
	yych = *++reader;
	switch (yych) {
	case 'l':	goto yy101;
	default:	goto yy43;
	}
yy52:
	YYDEBUG(52, *reader);
	yych = *++reader;
	switch (yych) {
	case 'a':	goto yy102;
	case 'u':	goto yy103;
	default:	goto yy43;
	}
yy53:
	YYDEBUG(53, *reader);
	yych = *++reader;
	switch (yych) {
	case 'f':	goto yy104;
	default:	goto yy43;
	}
yy54:
	YYDEBUG(54, *reader);
	yych = *++reader;
	switch (yych) {
	case 'o':	goto yy106;
	case 'u':	goto yy107;
	default:	goto yy43;
	}
yy55:
	YYDEBUG(55, *reader);
	yych = *++reader;
	switch (yych) {
	case 'r':	goto yy108;
	default:	goto yy43;
	}
yy56:
	YYDEBUG(56, *reader);
	yych = *++reader;
	switch (yych) {
	case 'r':	goto yy110;
	default:	goto yy43;
	}
yy57:
	YYDEBUG(57, *reader);
	yych = *++reader;
	switch (yych) {
	case 'r':	goto yy111;
	default:	goto yy43;
	}
yy58:
	YYDEBUG(58, *reader);
	yych = *++reader;
	switch (yych) {
	case 'a':	goto yy112;
	default:	goto yy43;
	}
yy59:
	YYDEBUG(59, *reader);
	yych = *++reader;
	switch (yych) {
	case 'h':	goto yy113;
	default:	goto yy43;
	}
yy60:
	YYDEBUG(60, *reader);
	++reader;
	YYDEBUG(61, *reader);
#line 206 "../re2c/lexer.re"
	{
        br_stack.push('{');
        PUT_LEXEME(LexemeType::LBrace)
      }
#line 686 "../src/lexer.cpp"
yy62:
	YYDEBUG(62, *reader);
	++reader;
	YYDEBUG(63, *reader);
#line 223 "../re2c/lexer.re"
	{
        if(br_stack.top() == '{'){
          br_stack.pop();
          if(lexemes.back().type == LexemeType::Newline){
            lexemes.pop_back();
          }
          PUT_LEXEME(LexemeType::RBrace)
        }else{
          errors->emplace_back(dynSprintf("line %d: Unexpected '}'.", line));
          PUT_LEXEME(LexemeType::Error);
        }
      }
#line 704 "../src/lexer.cpp"
yy64:
	YYDEBUG(64, *reader);
	++reader;
	YYDEBUG(65, *reader);
#line 192 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Neq)}
#line 711 "../src/lexer.cpp"
yy66:
	YYDEBUG(66, *reader);
	++reader;
	YYDEBUG(67, *reader);
#line 189 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::ModAssign)}
#line 718 "../src/lexer.cpp"
yy68:
	YYDEBUG(68, *reader);
	++reader;
	YYDEBUG(69, *reader);
#line 187 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::MulAssign)}
#line 725 "../src/lexer.cpp"
yy70:
	YYDEBUG(70, *reader);
	yych = *++reader;
	switch (yych) {
	case '=':	goto yy114;
	default:	goto yy71;
	}
yy71:
	YYDEBUG(71, *reader);
#line 183 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Append)}
#line 737 "../src/lexer.cpp"
yy72:
	YYDEBUG(72, *reader);
	++reader;
	YYDEBUG(73, *reader);
#line 185 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::AddAssign)}
#line 744 "../src/lexer.cpp"
yy74:
	YYDEBUG(74, *reader);
	++reader;
	YYDEBUG(75, *reader);
#line 186 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::SubAssign)}
#line 751 "../src/lexer.cpp"
yy76:
	YYDEBUG(76, *reader);
	yych = *++reader;
	YYDEBUG(77, *reader);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy76;
	case 'E':
	case 'e':	goto yy88;
	default:	goto yy78;
	}
yy78:
	YYDEBUG(78, *reader);
#line 169 "../re2c/lexer.re"
	{PUT_LEXEME(atof(token))}
#line 775 "../src/lexer.cpp"
yy79:
	YYDEBUG(79, *reader);
	++reader;
	YYDEBUG(80, *reader);
#line 153 "../re2c/lexer.re"
	{counter = 1; goto lex_block_comment;}
#line 782 "../src/lexer.cpp"
yy81:
	YYDEBUG(81, *reader);
	yych = *++reader;
	YYDEBUG(82, *reader);
	switch (yych) {
	case 0x00:
	case '\n':	goto yy83;
	default:	goto yy81;
	}
yy83:
	YYDEBUG(83, *reader);
#line 152 "../re2c/lexer.re"
	{continue;}
#line 796 "../src/lexer.cpp"
yy84:
	YYDEBUG(84, *reader);
	++reader;
	YYDEBUG(85, *reader);
#line 188 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::DivAssign)}
#line 803 "../src/lexer.cpp"
yy86:
	YYDEBUG(86, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':	goto yy116;
	default:	goto yy87;
	}
yy87:
	YYDEBUG(87, *reader);
	reader = marker;
	if (yyaccept == 0) {
		goto yy31;
	} else {
		goto yy78;
	}
yy88:
	YYDEBUG(88, *reader);
	yyaccept = 1;
	yych = *(marker = ++reader);
	switch (yych) {
	case '+':
	case '-':	goto yy119;
	default:	goto yy121;
	}
yy89:
	YYDEBUG(89, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy122;
	default:	goto yy87;
	}
yy90:
	YYDEBUG(90, *reader);
	yych = *++reader;
	switch (yych) {
	case '.':	goto yy125;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy126;
	default:	goto yy87;
	}
yy91:
	YYDEBUG(91, *reader);
	yych = *++reader;
	switch (yych) {
	case '>':	goto yy129;
	default:	goto yy92;
	}
yy92:
	YYDEBUG(92, *reader);
#line 196 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Leq)}
#line 883 "../src/lexer.cpp"
yy93:
	YYDEBUG(93, *reader);
	++reader;
	YYDEBUG(94, *reader);
#line 191 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Eq)}
#line 890 "../src/lexer.cpp"
yy95:
	YYDEBUG(95, *reader);
	++reader;
	YYDEBUG(96, *reader);
#line 195 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Geq)}
#line 897 "../src/lexer.cpp"
yy97:
	YYDEBUG(97, *reader);
	yych = *++reader;
	switch (yych) {
	case 'd':	goto yy131;
	default:	goto yy43;
	}
yy98:
	YYDEBUG(98, *reader);
	yych = *++reader;
	switch (yych) {
	case 's':	goto yy133;
	default:	goto yy43;
	}
yy99:
	YYDEBUG(99, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy100;
	default:	goto yy42;
	}
yy100:
	YYDEBUG(100, *reader);
#line 252 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Do)}
#line 987 "../src/lexer.cpp"
yy101:
	YYDEBUG(101, *reader);
	yych = *++reader;
	switch (yych) {
	case 's':	goto yy134;
	default:	goto yy43;
	}
yy102:
	YYDEBUG(102, *reader);
	yych = *++reader;
	switch (yych) {
	case 'l':	goto yy135;
	default:	goto yy43;
	}
yy103:
	YYDEBUG(103, *reader);
	yych = *++reader;
	switch (yych) {
	case 'n':	goto yy136;
	default:	goto yy43;
	}
yy104:
	YYDEBUG(104, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy105;
	default:	goto yy42;
	}
yy105:
	YYDEBUG(105, *reader);
#line 250 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::If)}
#line 1084 "../src/lexer.cpp"
yy106:
	YYDEBUG(106, *reader);
	yych = *++reader;
	switch (yych) {
	case 't':	goto yy137;
	default:	goto yy43;
	}
yy107:
	YYDEBUG(107, *reader);
	yych = *++reader;
	switch (yych) {
	case 'l':	goto yy139;
	default:	goto yy43;
	}
yy108:
	YYDEBUG(108, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy109;
	default:	goto yy42;
	}
yy109:
	YYDEBUG(109, *reader);
#line 264 "../re2c/lexer.re"
	{
        if(lexemes.back().type == LexemeType::Newline){
          lexemes.pop_back();
        }
        PUT_LEXEME(LexemeType::Or)
      }
#line 1179 "../src/lexer.cpp"
yy110:
	YYDEBUG(110, *reader);
	yych = *++reader;
	switch (yych) {
	case 'i':	goto yy140;
	default:	goto yy43;
	}
yy111:
	YYDEBUG(111, *reader);
	yych = *++reader;
	switch (yych) {
	case 'u':	goto yy141;
	default:	goto yy43;
	}
yy112:
	YYDEBUG(112, *reader);
	yych = *++reader;
	switch (yych) {
	case 'r':	goto yy142;
	default:	goto yy43;
	}
yy113:
	YYDEBUG(113, *reader);
	yych = *++reader;
	switch (yych) {
	case 'i':	goto yy144;
	default:	goto yy43;
	}
yy114:
	YYDEBUG(114, *reader);
	++reader;
	YYDEBUG(115, *reader);
#line 190 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::AppendAssign)}
#line 1214 "../src/lexer.cpp"
yy116:
	YYDEBUG(116, *reader);
	yych = *++reader;
	YYDEBUG(117, *reader);
	switch (yych) {
	case '0':
	case '1':	goto yy116;
	default:	goto yy118;
	}
yy118:
	YYDEBUG(118, *reader);
#line 157 "../re2c/lexer.re"
	{PUT_LEXEME(strtoull(token + 2, nullptr, 2))}
#line 1228 "../src/lexer.cpp"
yy119:
	YYDEBUG(119, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy120;
	default:	goto yy87;
	}
yy120:
	YYDEBUG(120, *reader);
	yych = *++reader;
yy121:
	YYDEBUG(121, *reader);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy120;
	default:	goto yy78;
	}
yy122:
	YYDEBUG(122, *reader);
	yych = *++reader;
	YYDEBUG(123, *reader);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy122;
	default:	goto yy124;
	}
yy124:
	YYDEBUG(124, *reader);
#line 158 "../re2c/lexer.re"
	{PUT_LEXEME(strtoull(token + 2, nullptr, 8))}
#line 1282 "../src/lexer.cpp"
yy125:
	YYDEBUG(125, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy145;
	default:	goto yy87;
	}
yy126:
	YYDEBUG(126, *reader);
	yych = *++reader;
	YYDEBUG(127, *reader);
	switch (yych) {
	case '.':	goto yy145;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy126;
	case 'P':
	case 'p':	goto yy88;
	default:	goto yy128;
	}
yy128:
	YYDEBUG(128, *reader);
#line 159 "../re2c/lexer.re"
	{PUT_LEXEME(strtoull(token + 2, nullptr, 16))}
#line 1347 "../src/lexer.cpp"
yy129:
	YYDEBUG(129, *reader);
	++reader;
	YYDEBUG(130, *reader);
#line 197 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Cmp)}
#line 1354 "../src/lexer.cpp"
yy131:
	YYDEBUG(131, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy132;
	default:	goto yy42;
	}
yy132:
	YYDEBUG(132, *reader);
#line 258 "../re2c/lexer.re"
	{
        if(lexemes.back().type == LexemeType::Newline){
          lexemes.pop_back();
        }
        PUT_LEXEME(LexemeType::And)
      }
#line 1435 "../src/lexer.cpp"
yy133:
	YYDEBUG(133, *reader);
	yych = *++reader;
	switch (yych) {
	case 'e':	goto yy147;
	default:	goto yy43;
	}
yy134:
	YYDEBUG(134, *reader);
	yych = *++reader;
	switch (yych) {
	case 'e':	goto yy148;
	default:	goto yy43;
	}
yy135:
	YYDEBUG(135, *reader);
	yych = *++reader;
	switch (yych) {
	case 's':	goto yy150;
	default:	goto yy43;
	}
yy136:
	YYDEBUG(136, *reader);
	yych = *++reader;
	switch (yych) {
	case 'c':	goto yy151;
	default:	goto yy43;
	}
yy137:
	YYDEBUG(137, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy138;
	default:	goto yy42;
	}
yy138:
	YYDEBUG(138, *reader);
#line 249 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Not)}
#line 1539 "../src/lexer.cpp"
yy139:
	YYDEBUG(139, *reader);
	yych = *++reader;
	switch (yych) {
	case 'l':	goto yy153;
	default:	goto yy43;
	}
yy140:
	YYDEBUG(140, *reader);
	yych = *++reader;
	switch (yych) {
	case 'n':	goto yy155;
	default:	goto yy43;
	}
yy141:
	YYDEBUG(141, *reader);
	yych = *++reader;
	switch (yych) {
	case 'e':	goto yy156;
	default:	goto yy43;
	}
yy142:
	YYDEBUG(142, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy143;
	default:	goto yy42;
	}
yy143:
	YYDEBUG(143, *reader);
#line 254 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Var)}
#line 1636 "../src/lexer.cpp"
yy144:
	YYDEBUG(144, *reader);
	yych = *++reader;
	switch (yych) {
	case 'l':	goto yy158;
	default:	goto yy43;
	}
yy145:
	YYDEBUG(145, *reader);
	yych = *++reader;
	YYDEBUG(146, *reader);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy145;
	case 'P':
	case 'p':	goto yy88;
	default:	goto yy78;
	}
yy147:
	YYDEBUG(147, *reader);
	yych = *++reader;
	switch (yych) {
	case 'r':	goto yy159;
	default:	goto yy43;
	}
yy148:
	YYDEBUG(148, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy149;
	default:	goto yy42;
	}
yy149:
	YYDEBUG(149, *reader);
#line 270 "../re2c/lexer.re"
	{
        if(lexemes.back().type == LexemeType::Newline){
          lexemes.pop_back();
        }
        PUT_LEXEME(LexemeType::Else)
      }
#line 1762 "../src/lexer.cpp"
yy150:
	YYDEBUG(150, *reader);
	yych = *++reader;
	switch (yych) {
	case 'e':	goto yy160;
	default:	goto yy43;
	}
yy151:
	YYDEBUG(151, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy152;
	default:	goto yy42;
	}
yy152:
	YYDEBUG(152, *reader);
#line 253 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Func)}
#line 1845 "../src/lexer.cpp"
yy153:
	YYDEBUG(153, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy154;
	default:	goto yy42;
	}
yy154:
	YYDEBUG(154, *reader);
#line 246 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Null)}
#line 1921 "../src/lexer.cpp"
yy155:
	YYDEBUG(155, *reader);
	yych = *++reader;
	switch (yych) {
	case 't':	goto yy162;
	default:	goto yy43;
	}
yy156:
	YYDEBUG(156, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy157;
	default:	goto yy42;
	}
yy157:
	YYDEBUG(157, *reader);
#line 247 "../re2c/lexer.re"
	{PUT_LEXEME(true)}
#line 2004 "../src/lexer.cpp"
yy158:
	YYDEBUG(158, *reader);
	yych = *++reader;
	switch (yych) {
	case 'e':	goto yy164;
	default:	goto yy43;
	}
yy159:
	YYDEBUG(159, *reader);
	yych = *++reader;
	switch (yych) {
	case 't':	goto yy166;
	default:	goto yy43;
	}
yy160:
	YYDEBUG(160, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy161;
	default:	goto yy42;
	}
yy161:
	YYDEBUG(161, *reader);
#line 248 "../re2c/lexer.re"
	{PUT_LEXEME(false)}
#line 2094 "../src/lexer.cpp"
yy162:
	YYDEBUG(162, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy163;
	default:	goto yy42;
	}
yy163:
	YYDEBUG(163, *reader);
#line 255 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Print)}
#line 2170 "../src/lexer.cpp"
yy164:
	YYDEBUG(164, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy165;
	default:	goto yy42;
	}
yy165:
	YYDEBUG(165, *reader);
#line 251 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::For)}
#line 2246 "../src/lexer.cpp"
yy166:
	YYDEBUG(166, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy167;
	default:	goto yy42;
	}
yy167:
	YYDEBUG(167, *reader);
#line 256 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Assert)}
#line 2322 "../src/lexer.cpp"
}
#line 305 "../re2c/lexer.re"

  
  lex_string: {
      std::string str;
      
    lex_string_L1:
      
#line 2332 "../src/lexer.cpp"
{
	char yych;
	unsigned int yyaccept = 0;
	YYDEBUG(168, *reader);
	yych = *reader;
	switch (yych) {
	case 0x00:	goto yy170;
	case '\n':	goto yy174;
	case '"':	goto yy176;
	case '\\':	goto yy178;
	default:	goto yy172;
	}
yy170:
	YYDEBUG(170, *reader);
	++reader;
	YYDEBUG(171, *reader);
#line 313 "../re2c/lexer.re"
	{break;}
#line 2351 "../src/lexer.cpp"
yy172:
	YYDEBUG(172, *reader);
	++reader;
	YYDEBUG(173, *reader);
#line 315 "../re2c/lexer.re"
	{
          str.push_back(yych);
          goto lex_string_L1;
        }
#line 2361 "../src/lexer.cpp"
yy174:
	YYDEBUG(174, *reader);
	++reader;
yy175:
	YYDEBUG(175, *reader);
#line 312 "../re2c/lexer.re"
	{break;}
#line 2369 "../src/lexer.cpp"
yy176:
	YYDEBUG(176, *reader);
	++reader;
	YYDEBUG(177, *reader);
#line 320 "../re2c/lexer.re"
	{
          StringView view(str.c_str(), str.size());
          String* str;
          auto it = this->string_table.find(view);
          if(it == this->string_table.end()){
            str = this->string_table.insert(
              std::make_pair(
                view,
                rc_ptr<String>(make_new<String>(view.first, view.second))
              )
            ).first->second.get();
          }else{
            str = it->second.get();
          }
          PLACE_LEXEME(str);
          continue;
        }
#line 2392 "../src/lexer.cpp"
yy178:
	YYDEBUG(178, *reader);
	yyaccept = 0;
	yych = *(marker = ++reader);
	switch (yych) {
	case '\n':	goto yy179;
	case '"':	goto yy181;
	case '\'':	goto yy183;
	case '0':
	case '1':
	case '2':
	case '3':	goto yy185;
	case '4':
	case '5':
	case '6':
	case '7':	goto yy187;
	case '?':	goto yy188;
	case 'U':	goto yy190;
	case '\\':	goto yy192;
	case 'a':	goto yy194;
	case 'b':	goto yy196;
	case 'f':	goto yy198;
	case 'n':	goto yy200;
	case 'r':	goto yy202;
	case 't':	goto yy204;
	case 'u':	goto yy206;
	case 'v':	goto yy207;
	case 'x':	goto yy209;
	default:	goto yy175;
	}
yy179:
	YYDEBUG(179, *reader);
	++reader;
	YYDEBUG(180, *reader);
#line 349 "../re2c/lexer.re"
	{goto lex_string_L1;}
#line 2429 "../src/lexer.cpp"
yy181:
	YYDEBUG(181, *reader);
	++reader;
	YYDEBUG(182, *reader);
#line 348 "../re2c/lexer.re"
	{str.push_back('\"'); goto lex_string_L1;}
#line 2436 "../src/lexer.cpp"
yy183:
	YYDEBUG(183, *reader);
	++reader;
	YYDEBUG(184, *reader);
#line 347 "../re2c/lexer.re"
	{str.push_back('\''); goto lex_string_L1;}
#line 2443 "../src/lexer.cpp"
yy185:
	YYDEBUG(185, *reader);
	yyaccept = 1;
	yych = *(marker = ++reader);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy210;
	default:	goto yy186;
	}
yy186:
	YYDEBUG(186, *reader);
#line 351 "../re2c/lexer.re"
	{str.push_back(*(reader - 1)); goto lex_string_L1;}
#line 2463 "../src/lexer.cpp"
yy187:
	YYDEBUG(187, *reader);
	++reader;
	goto yy186;
yy188:
	YYDEBUG(188, *reader);
	++reader;
	YYDEBUG(189, *reader);
#line 346 "../re2c/lexer.re"
	{str.push_back('\?'); goto lex_string_L1;}
#line 2474 "../src/lexer.cpp"
yy190:
	YYDEBUG(190, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy211;
	default:	goto yy191;
	}
yy191:
	YYDEBUG(191, *reader);
	reader = marker;
	if (yyaccept == 0) {
		goto yy175;
	} else {
		goto yy186;
	}
yy192:
	YYDEBUG(192, *reader);
	++reader;
	YYDEBUG(193, *reader);
#line 345 "../re2c/lexer.re"
	{str.push_back('\\'); goto lex_string_L1;}
#line 2517 "../src/lexer.cpp"
yy194:
	YYDEBUG(194, *reader);
	++reader;
	YYDEBUG(195, *reader);
#line 338 "../re2c/lexer.re"
	{str.push_back('\a'); goto lex_string_L1;}
#line 2524 "../src/lexer.cpp"
yy196:
	YYDEBUG(196, *reader);
	++reader;
	YYDEBUG(197, *reader);
#line 339 "../re2c/lexer.re"
	{str.push_back('\b'); goto lex_string_L1;}
#line 2531 "../src/lexer.cpp"
yy198:
	YYDEBUG(198, *reader);
	++reader;
	YYDEBUG(199, *reader);
#line 340 "../re2c/lexer.re"
	{str.push_back('\f'); goto lex_string_L1;}
#line 2538 "../src/lexer.cpp"
yy200:
	YYDEBUG(200, *reader);
	++reader;
	YYDEBUG(201, *reader);
#line 341 "../re2c/lexer.re"
	{str.push_back('\n'); goto lex_string_L1;}
#line 2545 "../src/lexer.cpp"
yy202:
	YYDEBUG(202, *reader);
	++reader;
	YYDEBUG(203, *reader);
#line 342 "../re2c/lexer.re"
	{str.push_back('\r'); goto lex_string_L1;}
#line 2552 "../src/lexer.cpp"
yy204:
	YYDEBUG(204, *reader);
	++reader;
	YYDEBUG(205, *reader);
#line 343 "../re2c/lexer.re"
	{str.push_back('\t'); goto lex_string_L1;}
#line 2559 "../src/lexer.cpp"
yy206:
	YYDEBUG(206, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy212;
	default:	goto yy191;
	}
yy207:
	YYDEBUG(207, *reader);
	++reader;
	YYDEBUG(208, *reader);
#line 344 "../re2c/lexer.re"
	{str.push_back('\v'); goto lex_string_L1;}
#line 2594 "../src/lexer.cpp"
yy209:
	YYDEBUG(209, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy213;
	default:	goto yy191;
	}
yy210:
	YYDEBUG(210, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy214;
	default:	goto yy191;
	}
yy211:
	YYDEBUG(211, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy216;
	default:	goto yy191;
	}
yy212:
	YYDEBUG(212, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy217;
	default:	goto yy191;
	}
yy213:
	YYDEBUG(213, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy218;
	default:	goto yy191;
	}
yy214:
	YYDEBUG(214, *reader);
	++reader;
	YYDEBUG(215, *reader);
#line 353 "../re2c/lexer.re"
	{
          str.push_back(
            (*(reader - 3) * 0x40) |
            (*(reader - 2) * 0x8) |
            (*reader - 1)
          );
          goto lex_string_L1;
        }
#line 2734 "../src/lexer.cpp"
yy216:
	YYDEBUG(216, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy220;
	default:	goto yy191;
	}
yy217:
	YYDEBUG(217, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy221;
	default:	goto yy191;
	}
yy218:
	YYDEBUG(218, *reader);
	++reader;
	YYDEBUG(219, *reader);
#line 361 "../re2c/lexer.re"
	{
          str.push_back((*(reader - 2) * 0x10) | (*reader - 1));
          goto lex_string_L1;
        }
#line 2800 "../src/lexer.cpp"
yy220:
	YYDEBUG(220, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy222;
	default:	goto yy191;
	}
yy221:
	YYDEBUG(221, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy223;
	default:	goto yy191;
	}
yy222:
	YYDEBUG(222, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy225;
	default:	goto yy191;
	}
yy223:
	YYDEBUG(223, *reader);
	++reader;
	YYDEBUG(224, *reader);
#line 365 "../re2c/lexer.re"
	{
          enterUtf8CodePoint_<4>(&str, reader);
          goto lex_string_L1;
        }
#line 2894 "../src/lexer.cpp"
yy225:
	YYDEBUG(225, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy226;
	default:	goto yy191;
	}
yy226:
	YYDEBUG(226, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy227;
	default:	goto yy191;
	}
yy227:
	YYDEBUG(227, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy228;
	default:	goto yy191;
	}
yy228:
	YYDEBUG(228, *reader);
	++reader;
	YYDEBUG(229, *reader);
#line 369 "../re2c/lexer.re"
	{
          enterUtf8CodePoint_<8>(&str, reader);
          goto lex_string_L1;
        }
#line 2988 "../src/lexer.cpp"
}
#line 373 "../re2c/lexer.re"

    }
    
  lex_block_comment:
    
#line 2996 "../src/lexer.cpp"
{
	char yych;
	YYDEBUG(230, *reader);
	yych = *reader;
	switch (yych) {
	case 0x00:	goto yy232;
	case '\n':	goto yy236;
	case '*':	goto yy238;
	case '/':	goto yy239;
	default:	goto yy234;
	}
yy232:
	YYDEBUG(232, *reader);
	++reader;
	YYDEBUG(233, *reader);
#line 378 "../re2c/lexer.re"
	{break;}
#line 3014 "../src/lexer.cpp"
yy234:
	YYDEBUG(234, *reader);
	++reader;
yy235:
	YYDEBUG(235, *reader);
#line 379 "../re2c/lexer.re"
	{goto lex_block_comment;}
#line 3022 "../src/lexer.cpp"
yy236:
	YYDEBUG(236, *reader);
	++reader;
	YYDEBUG(237, *reader);
#line 382 "../re2c/lexer.re"
	{
        ++line;
        line_start = reader;
        if((br_stack.top() == '{'
        || br_stack.top() == '#')
        && isStopLexeme(lexemes.back())){
          PLACE_LEXEME(LexemeType::Newline);
        }
        goto lex_block_comment;
      }
#line 3038 "../src/lexer.cpp"
yy238:
	YYDEBUG(238, *reader);
	yych = *++reader;
	switch (yych) {
	case '/':	goto yy240;
	default:	goto yy235;
	}
yy239:
	YYDEBUG(239, *reader);
	yych = *++reader;
	switch (yych) {
	case '*':	goto yy242;
	default:	goto yy235;
	}
yy240:
	YYDEBUG(240, *reader);
	++reader;
	YYDEBUG(241, *reader);
#line 381 "../re2c/lexer.re"
	{if(--counter) goto lex_block_comment; else continue;}
#line 3059 "../src/lexer.cpp"
yy242:
	YYDEBUG(242, *reader);
	++reader;
	YYDEBUG(243, *reader);
#line 380 "../re2c/lexer.re"
	{++counter; goto lex_block_comment;}
#line 3066 "../src/lexer.cpp"
}
#line 392 "../re2c/lexer.re"

  }
  
  lexemes.emplace_back(LexemeType::End, std::make_pair(line, reader - line_start));
  
  #undef PLACE_LEXEME
  #undef PUT_LEXEME
  
  return lexemes;
}
