/* Generated by re2c 1.0.3 on Fri Jan 12 00:48:55 2018 */
#line 1 "../re2c/lexer.re"
#include "lexer.h"

#include <cstdint>

namespace{
  
  constexpr uint64_t utf8Mask_(int bytes){
    if(bytes >= 2){
      int mask1 = 0x8000, mask2 = 0x80;
      for(; bytes > 2; --bytes){
        mask1 = (mask1 << 8) | (mask1 << 7);
        mask2 = (mask2 << 8) | 0x80;
      }
      return mask1 | mask2;
    }else return 0;
  }
  
  template<int bytes>
  inline uint64_t splitUtf8CodePoint_(uint64_t code_point){
    uint64_t mask = 0x3f;
    for(int i = 1; i < bytes; ++i){
      code_point = (code_point & mask) | ((code_point & ~mask) << 2);
      mask = (mask << 8) | 0xff;
    }
    return code_point;
  }
  
  template<int chars>
  inline void enterUtf8CodePoint_(std::string* dest, const char* code){
    uint64_t code_point;
    code -= chars;
    for(int i = 0; i < chars; ++i){
      code_point <<= 8;
      if(isdigit(*code)){
        code_point |= (*code) - '0';
      }else{
        code_point |= (*code | 0x20) - 'a' + 10;
      }
      ++code;
    }
    if(code_point < 0x80){
      dest->push_back((char)code_point);
      return;
    }else{
      int bytes = 2;
      for(uint64_t cp = code_point >> 11; cp > 0; ++bytes, cp >> 5);
      
      switch(bytes){
      case 2:
        code_point = splitUtf8CodePoint_<2>(code_point) | utf8Mask_(2);
        goto write_2_bytes;
      case 3:
        code_point = splitUtf8CodePoint_<3>(code_point) | utf8Mask_(3);
        goto write_3_bytes;
      case 4:
        code_point = splitUtf8CodePoint_<4>(code_point) | utf8Mask_(4);
        goto write_4_bytes;
      case 5:
        code_point = splitUtf8CodePoint_<5>(code_point) | utf8Mask_(5);
        goto write_5_bytes;
      case 6:
        code_point = splitUtf8CodePoint_<6>(code_point) | utf8Mask_(6);
        goto write_6_bytes;
      case 7:
        code_point = splitUtf8CodePoint_<7>(code_point) | utf8Mask_(7);
        goto write_7_bytes;
      }
      
    write_7_bytes:
      dest->push_back(code[-7]);
    write_6_bytes:
      dest->push_back(code[-6]);
    write_5_bytes:
      dest->push_back(code[-5]);
    write_4_bytes:
      dest->push_back(code[-4]);
    write_3_bytes:
      dest->push_back(code[-3]);
    write_2_bytes:
      dest->push_back(code[-2]);
      dest->push_back(code[-1]);
    }
  }
}

Lexer::Lexer(const char* mem){
  this->mem_ = mem;
  this->old_reader_ = nullptr;
  this->reader_ = mem;
}

Token* Lexer::next(){
  const char* marker;
  const char* token;
  
  int counter = 0;
  
  this->old_reader_ = this->reader_;
  
  #define YYDEBUG(state, current)
  
  for(;;){
    token = this->reader_;
    
    #line 111 "../re2c/lexer.re"

    
    
#line 112 "../src/lexer.cpp"
{
	char yych;
	unsigned int yyaccept = 0;
	YYDEBUG(0, *this->reader_);
	yych = *this->reader_;
	switch (yych) {
	case 0x00:	goto yy2;
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case '#':
	case '&':
	case '\'':
	case '?':
	case '@':
	case '\\':
	case '^':
	case '`':
	case '|':
	case '~':
	case 0x7F:	goto yy4;
	case '\t':
	case '\v':
	case '\f':
	case '\r':
	case ' ':	goto yy6;
	case '\n':	goto yy8;
	case '!':	goto yy10;
	case '"':	goto yy11;
	case '$':	goto yy13;
	case '%':	goto yy14;
	case '(':	goto yy16;
	case ')':	goto yy18;
	case '*':	goto yy20;
	case '+':	goto yy22;
	case ',':	goto yy24;
	case '-':	goto yy26;
	case '.':	goto yy28;
	case '/':	goto yy29;
	case '0':	goto yy31;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy33;
	case ':':	goto yy35;
	case ';':	goto yy37;
	case '<':	goto yy39;
	case '=':	goto yy41;
	case '>':	goto yy43;
	case '[':	goto yy48;
	case ']':	goto yy50;
	case 'a':	goto yy52;
	case 'e':	goto yy53;
	case 'f':	goto yy54;
	case 'i':	goto yy55;
	case 'n':	goto yy56;
	case 'o':	goto yy57;
	case 'p':	goto yy58;
	case 't':	goto yy59;
	case 'v':	goto yy60;
	case 'w':	goto yy61;
	case '{':	goto yy62;
	case '}':	goto yy64;
	default:	goto yy45;
	}
yy2:
	YYDEBUG(2, *this->reader_);
	++this->reader_;
	YYDEBUG(3, *this->reader_);
#line 114 "../re2c/lexer.re"
	{break;}
#line 212 "../src/lexer.cpp"
yy4:
	YYDEBUG(4, *this->reader_);
	++this->reader_;
yy5:
	YYDEBUG(5, *this->reader_);
#line 116 "../re2c/lexer.re"
	{break;}
#line 220 "../src/lexer.cpp"
yy6:
	YYDEBUG(6, *this->reader_);
	++this->reader_;
	YYDEBUG(7, *this->reader_);
#line 119 "../re2c/lexer.re"
	{continue;}
#line 227 "../src/lexer.cpp"
yy8:
	YYDEBUG(8, *this->reader_);
	++this->reader_;
	YYDEBUG(9, *this->reader_);
#line 120 "../re2c/lexer.re"
	{return new Token(TokenType::NewlineToken);}
#line 234 "../src/lexer.cpp"
yy10:
	YYDEBUG(10, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '=':	goto yy66;
	default:	goto yy5;
	}
yy11:
	YYDEBUG(11, *this->reader_);
	++this->reader_;
	YYDEBUG(12, *this->reader_);
#line 153 "../re2c/lexer.re"
	{
        goto lex_string;
      }
#line 250 "../src/lexer.cpp"
yy13:
	YYDEBUG(13, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy68;
	default:	goto yy5;
	}
yy14:
	YYDEBUG(14, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '=':	goto yy71;
	default:	goto yy15;
	}
yy15:
	YYDEBUG(15, *this->reader_);
#line 163 "../re2c/lexer.re"
	{return new Token(TokenType::ModToken);}
#line 277 "../src/lexer.cpp"
yy16:
	YYDEBUG(16, *this->reader_);
	++this->reader_;
	YYDEBUG(17, *this->reader_);
#line 179 "../re2c/lexer.re"
	{return new Token(TokenType::LParenToken);}
#line 284 "../src/lexer.cpp"
yy18:
	YYDEBUG(18, *this->reader_);
	++this->reader_;
	YYDEBUG(19, *this->reader_);
#line 180 "../re2c/lexer.re"
	{return new Token(TokenType::RParenToken);}
#line 291 "../src/lexer.cpp"
yy20:
	YYDEBUG(20, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '=':	goto yy73;
	default:	goto yy21;
	}
yy21:
	YYDEBUG(21, *this->reader_);
#line 161 "../re2c/lexer.re"
	{return new Token(TokenType::MulToken);}
#line 303 "../src/lexer.cpp"
yy22:
	YYDEBUG(22, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '+':	goto yy75;
	case '=':	goto yy77;
	default:	goto yy23;
	}
yy23:
	YYDEBUG(23, *this->reader_);
#line 159 "../re2c/lexer.re"
	{return new Token(TokenType::PlusToken);}
#line 316 "../src/lexer.cpp"
yy24:
	YYDEBUG(24, *this->reader_);
	++this->reader_;
	YYDEBUG(25, *this->reader_);
#line 185 "../re2c/lexer.re"
	{return new Token(TokenType::CommaToken);}
#line 323 "../src/lexer.cpp"
yy26:
	YYDEBUG(26, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '=':	goto yy79;
	default:	goto yy27;
	}
yy27:
	YYDEBUG(27, *this->reader_);
#line 160 "../re2c/lexer.re"
	{return new Token(TokenType::MinusToken);}
#line 335 "../src/lexer.cpp"
yy28:
	YYDEBUG(28, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy81;
	default:	goto yy5;
	}
yy29:
	YYDEBUG(29, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '*':	goto yy84;
	case '/':	goto yy86;
	case '=':	goto yy89;
	default:	goto yy30;
	}
yy30:
	YYDEBUG(30, *this->reader_);
#line 162 "../re2c/lexer.re"
	{return new Token(TokenType::DivToken);}
#line 365 "../src/lexer.cpp"
yy31:
	YYDEBUG(31, *this->reader_);
	yyaccept = 0;
	yych = *(marker = ++this->reader_);
	switch (yych) {
	case 'B':
	case 'b':	goto yy91;
	case 'O':
	case 'o':	goto yy94;
	case 'X':
	case 'x':	goto yy95;
	default:	goto yy34;
	}
yy32:
	YYDEBUG(32, *this->reader_);
#line 127 "../re2c/lexer.re"
	{
        return new Token(strtoull(token, nullptr, 10));
      }
#line 385 "../src/lexer.cpp"
yy33:
	YYDEBUG(33, *this->reader_);
	yych = *++this->reader_;
yy34:
	YYDEBUG(34, *this->reader_);
	switch (yych) {
	case '.':	goto yy81;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy33;
	case 'E':
	case 'e':	goto yy93;
	default:	goto yy32;
	}
yy35:
	YYDEBUG(35, *this->reader_);
	++this->reader_;
	YYDEBUG(36, *this->reader_);
#line 188 "../re2c/lexer.re"
	{return new Token(TokenType::ColonToken);}
#line 413 "../src/lexer.cpp"
yy37:
	YYDEBUG(37, *this->reader_);
	++this->reader_;
	YYDEBUG(38, *this->reader_);
#line 187 "../re2c/lexer.re"
	{return new Token(TokenType::SemicolonToken);}
#line 420 "../src/lexer.cpp"
yy39:
	YYDEBUG(39, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '-':	goto yy96;
	case '=':	goto yy98;
	default:	goto yy40;
	}
yy40:
	YYDEBUG(40, *this->reader_);
#line 175 "../re2c/lexer.re"
	{return new Token(TokenType::LtToken);}
#line 433 "../src/lexer.cpp"
yy41:
	YYDEBUG(41, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '=':	goto yy100;
	default:	goto yy42;
	}
yy42:
	YYDEBUG(42, *this->reader_);
#line 165 "../re2c/lexer.re"
	{return new Token(TokenType::AssignToken);}
#line 445 "../src/lexer.cpp"
yy43:
	YYDEBUG(43, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '=':	goto yy102;
	default:	goto yy44;
	}
yy44:
	YYDEBUG(44, *this->reader_);
#line 174 "../re2c/lexer.re"
	{return new Token(TokenType::GtToken);}
#line 457 "../src/lexer.cpp"
yy45:
	YYDEBUG(45, *this->reader_);
	yych = *++this->reader_;
yy46:
	YYDEBUG(46, *this->reader_);
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy47;
	default:	goto yy45;
	}
yy47:
	YYDEBUG(47, *this->reader_);
#line 205 "../re2c/lexer.re"
	{
        StringView view(token, this->reader_);
        String* str;
        auto it = this->string_table.find(view);
        if(it == this->string_table.end()){
          str = this->string_table.insert(
            std::make_pair(
              view,
              rc_ptr<String>(make_new<String>(view.first, view.second))
            )
          ).first->second.get();
        }else{
          str = it->second.get();
        }
        return new Token(TokenType::IdentifierToken, str);
      }
#line 550 "../src/lexer.cpp"
yy48:
	YYDEBUG(48, *this->reader_);
	++this->reader_;
	YYDEBUG(49, *this->reader_);
#line 183 "../re2c/lexer.re"
	{return new Token(TokenType::LBracketToken);}
#line 557 "../src/lexer.cpp"
yy50:
	YYDEBUG(50, *this->reader_);
	++this->reader_;
	YYDEBUG(51, *this->reader_);
#line 184 "../re2c/lexer.re"
	{return new Token(TokenType::RBracketToken);}
#line 564 "../src/lexer.cpp"
yy52:
	YYDEBUG(52, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'n':	goto yy104;
	default:	goto yy46;
	}
yy53:
	YYDEBUG(53, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'l':	goto yy105;
	default:	goto yy46;
	}
yy54:
	YYDEBUG(54, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'a':	goto yy106;
	case 'u':	goto yy107;
	default:	goto yy46;
	}
yy55:
	YYDEBUG(55, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'f':	goto yy108;
	default:	goto yy46;
	}
yy56:
	YYDEBUG(56, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'o':	goto yy110;
	case 'u':	goto yy111;
	default:	goto yy46;
	}
yy57:
	YYDEBUG(57, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'r':	goto yy112;
	default:	goto yy46;
	}
yy58:
	YYDEBUG(58, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'r':	goto yy114;
	default:	goto yy46;
	}
yy59:
	YYDEBUG(59, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'r':	goto yy115;
	default:	goto yy46;
	}
yy60:
	YYDEBUG(60, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'a':	goto yy116;
	default:	goto yy46;
	}
yy61:
	YYDEBUG(61, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'h':	goto yy117;
	default:	goto yy46;
	}
yy62:
	YYDEBUG(62, *this->reader_);
	++this->reader_;
	YYDEBUG(63, *this->reader_);
#line 181 "../re2c/lexer.re"
	{return new Token(TokenType::LBraceToken);}
#line 643 "../src/lexer.cpp"
yy64:
	YYDEBUG(64, *this->reader_);
	++this->reader_;
	YYDEBUG(65, *this->reader_);
#line 182 "../re2c/lexer.re"
	{return new Token(TokenType::RBraceToken);}
#line 650 "../src/lexer.cpp"
yy66:
	YYDEBUG(66, *this->reader_);
	++this->reader_;
	YYDEBUG(67, *this->reader_);
#line 173 "../re2c/lexer.re"
	{return new Token(TokenType::NeqToken);}
#line 657 "../src/lexer.cpp"
yy68:
	YYDEBUG(68, *this->reader_);
	yych = *++this->reader_;
	YYDEBUG(69, *this->reader_);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy68;
	default:	goto yy70;
	}
yy70:
	YYDEBUG(70, *this->reader_);
#line 223 "../re2c/lexer.re"
	{
        return new Token(TokenType::ParamToken, strtoull(token + 1, nullptr, 10));
      }
#line 681 "../src/lexer.cpp"
yy71:
	YYDEBUG(71, *this->reader_);
	++this->reader_;
	YYDEBUG(72, *this->reader_);
#line 170 "../re2c/lexer.re"
	{return new Token(TokenType::ModAssignToken);}
#line 688 "../src/lexer.cpp"
yy73:
	YYDEBUG(73, *this->reader_);
	++this->reader_;
	YYDEBUG(74, *this->reader_);
#line 168 "../re2c/lexer.re"
	{return new Token(TokenType::MulAssignToken);}
#line 695 "../src/lexer.cpp"
yy75:
	YYDEBUG(75, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '=':	goto yy118;
	default:	goto yy76;
	}
yy76:
	YYDEBUG(76, *this->reader_);
#line 164 "../re2c/lexer.re"
	{return new Token(TokenType::AppendToken);}
#line 707 "../src/lexer.cpp"
yy77:
	YYDEBUG(77, *this->reader_);
	++this->reader_;
	YYDEBUG(78, *this->reader_);
#line 166 "../re2c/lexer.re"
	{return new Token(TokenType::PlusAssignToken);}
#line 714 "../src/lexer.cpp"
yy79:
	YYDEBUG(79, *this->reader_);
	++this->reader_;
	YYDEBUG(80, *this->reader_);
#line 167 "../re2c/lexer.re"
	{return new Token(TokenType::MinusAssignToken);}
#line 721 "../src/lexer.cpp"
yy81:
	YYDEBUG(81, *this->reader_);
	yych = *++this->reader_;
	YYDEBUG(82, *this->reader_);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy81;
	case 'E':
	case 'e':	goto yy93;
	default:	goto yy83;
	}
yy83:
	YYDEBUG(83, *this->reader_);
#line 148 "../re2c/lexer.re"
	{
        return new Token(atof(token));
      }
#line 747 "../src/lexer.cpp"
yy84:
	YYDEBUG(84, *this->reader_);
	++this->reader_;
	YYDEBUG(85, *this->reader_);
#line 124 "../re2c/lexer.re"
	{counter = 1; goto lex_block_comment;}
#line 754 "../src/lexer.cpp"
yy86:
	YYDEBUG(86, *this->reader_);
	yych = *++this->reader_;
	YYDEBUG(87, *this->reader_);
	switch (yych) {
	case 0x00:
	case '\n':	goto yy88;
	default:	goto yy86;
	}
yy88:
	YYDEBUG(88, *this->reader_);
#line 123 "../re2c/lexer.re"
	{continue;}
#line 768 "../src/lexer.cpp"
yy89:
	YYDEBUG(89, *this->reader_);
	++this->reader_;
	YYDEBUG(90, *this->reader_);
#line 169 "../re2c/lexer.re"
	{return new Token(TokenType::DivAssignToken);}
#line 775 "../src/lexer.cpp"
yy91:
	YYDEBUG(91, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':	goto yy120;
	default:	goto yy92;
	}
yy92:
	YYDEBUG(92, *this->reader_);
	this->reader_ = marker;
	if (yyaccept == 0) {
		goto yy32;
	} else {
		goto yy83;
	}
yy93:
	YYDEBUG(93, *this->reader_);
	yyaccept = 1;
	yych = *(marker = ++this->reader_);
	switch (yych) {
	case '+':
	case '-':	goto yy123;
	default:	goto yy125;
	}
yy94:
	YYDEBUG(94, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy126;
	default:	goto yy92;
	}
yy95:
	YYDEBUG(95, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '.':	goto yy129;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy130;
	default:	goto yy92;
	}
yy96:
	YYDEBUG(96, *this->reader_);
	++this->reader_;
	YYDEBUG(97, *this->reader_);
#line 158 "../re2c/lexer.re"
	{return new Token(TokenType::InsertToken);}
#line 850 "../src/lexer.cpp"
yy98:
	YYDEBUG(98, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '>':	goto yy133;
	default:	goto yy99;
	}
yy99:
	YYDEBUG(99, *this->reader_);
#line 177 "../re2c/lexer.re"
	{return new Token(TokenType::LeqToken);}
#line 862 "../src/lexer.cpp"
yy100:
	YYDEBUG(100, *this->reader_);
	++this->reader_;
	YYDEBUG(101, *this->reader_);
#line 172 "../re2c/lexer.re"
	{return new Token(TokenType::EqToken);}
#line 869 "../src/lexer.cpp"
yy102:
	YYDEBUG(102, *this->reader_);
	++this->reader_;
	YYDEBUG(103, *this->reader_);
#line 176 "../re2c/lexer.re"
	{return new Token(TokenType::GeqToken);}
#line 876 "../src/lexer.cpp"
yy104:
	YYDEBUG(104, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'd':	goto yy135;
	default:	goto yy46;
	}
yy105:
	YYDEBUG(105, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 's':	goto yy137;
	default:	goto yy46;
	}
yy106:
	YYDEBUG(106, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'l':	goto yy138;
	default:	goto yy46;
	}
yy107:
	YYDEBUG(107, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'n':	goto yy139;
	default:	goto yy46;
	}
yy108:
	YYDEBUG(108, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy109;
	default:	goto yy45;
	}
yy109:
	YYDEBUG(109, *this->reader_);
#line 198 "../re2c/lexer.re"
	{return new Token(TokenType::IfToken);}
#line 980 "../src/lexer.cpp"
yy110:
	YYDEBUG(110, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 't':	goto yy140;
	default:	goto yy46;
	}
yy111:
	YYDEBUG(111, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'l':	goto yy142;
	default:	goto yy46;
	}
yy112:
	YYDEBUG(112, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy113;
	default:	goto yy45;
	}
yy113:
	YYDEBUG(113, *this->reader_);
#line 197 "../re2c/lexer.re"
	{return new Token(TokenType::OrToken);}
#line 1070 "../src/lexer.cpp"
yy114:
	YYDEBUG(114, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'i':	goto yy143;
	default:	goto yy46;
	}
yy115:
	YYDEBUG(115, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'u':	goto yy144;
	default:	goto yy46;
	}
yy116:
	YYDEBUG(116, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'r':	goto yy145;
	default:	goto yy46;
	}
yy117:
	YYDEBUG(117, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'i':	goto yy147;
	default:	goto yy46;
	}
yy118:
	YYDEBUG(118, *this->reader_);
	++this->reader_;
	YYDEBUG(119, *this->reader_);
#line 171 "../re2c/lexer.re"
	{return new Token(TokenType::AppendAssignToken);}
#line 1105 "../src/lexer.cpp"
yy120:
	YYDEBUG(120, *this->reader_);
	yych = *++this->reader_;
	YYDEBUG(121, *this->reader_);
	switch (yych) {
	case '0':
	case '1':	goto yy120;
	default:	goto yy122;
	}
yy122:
	YYDEBUG(122, *this->reader_);
#line 130 "../re2c/lexer.re"
	{
        return new Token(strtoull(token + 2, nullptr, 2));
      }
#line 1121 "../src/lexer.cpp"
yy123:
	YYDEBUG(123, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy124;
	default:	goto yy92;
	}
yy124:
	YYDEBUG(124, *this->reader_);
	yych = *++this->reader_;
yy125:
	YYDEBUG(125, *this->reader_);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy124;
	default:	goto yy83;
	}
yy126:
	YYDEBUG(126, *this->reader_);
	yych = *++this->reader_;
	YYDEBUG(127, *this->reader_);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy126;
	default:	goto yy128;
	}
yy128:
	YYDEBUG(128, *this->reader_);
#line 133 "../re2c/lexer.re"
	{
        return new Token(strtoull(token + 2, nullptr, 8));
      }
#line 1177 "../src/lexer.cpp"
yy129:
	YYDEBUG(129, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy148;
	default:	goto yy92;
	}
yy130:
	YYDEBUG(130, *this->reader_);
	yych = *++this->reader_;
	YYDEBUG(131, *this->reader_);
	switch (yych) {
	case '.':	goto yy148;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy130;
	case 'P':
	case 'p':	goto yy93;
	default:	goto yy132;
	}
yy132:
	YYDEBUG(132, *this->reader_);
#line 136 "../re2c/lexer.re"
	{
        return new Token(strtoull(token + 2, nullptr, 16));
      }
#line 1244 "../src/lexer.cpp"
yy133:
	YYDEBUG(133, *this->reader_);
	++this->reader_;
	YYDEBUG(134, *this->reader_);
#line 178 "../re2c/lexer.re"
	{return new Token(TokenType::CmpToken);}
#line 1251 "../src/lexer.cpp"
yy135:
	YYDEBUG(135, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy136;
	default:	goto yy45;
	}
yy136:
	YYDEBUG(136, *this->reader_);
#line 196 "../re2c/lexer.re"
	{return new Token(TokenType::AndToken);}
#line 1327 "../src/lexer.cpp"
yy137:
	YYDEBUG(137, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'e':	goto yy150;
	default:	goto yy46;
	}
yy138:
	YYDEBUG(138, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 's':	goto yy152;
	default:	goto yy46;
	}
yy139:
	YYDEBUG(139, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'c':	goto yy153;
	default:	goto yy46;
	}
yy140:
	YYDEBUG(140, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy141;
	default:	goto yy45;
	}
yy141:
	YYDEBUG(141, *this->reader_);
#line 195 "../re2c/lexer.re"
	{return new Token(TokenType::NotToken);}
#line 1424 "../src/lexer.cpp"
yy142:
	YYDEBUG(142, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'l':	goto yy155;
	default:	goto yy46;
	}
yy143:
	YYDEBUG(143, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'n':	goto yy157;
	default:	goto yy46;
	}
yy144:
	YYDEBUG(144, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'e':	goto yy158;
	default:	goto yy46;
	}
yy145:
	YYDEBUG(145, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy146;
	default:	goto yy45;
	}
yy146:
	YYDEBUG(146, *this->reader_);
#line 191 "../re2c/lexer.re"
	{return new Token(TokenType::VarToken);}
#line 1521 "../src/lexer.cpp"
yy147:
	YYDEBUG(147, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'l':	goto yy160;
	default:	goto yy46;
	}
yy148:
	YYDEBUG(148, *this->reader_);
	yych = *++this->reader_;
	YYDEBUG(149, *this->reader_);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy148;
	case 'P':
	case 'p':	goto yy93;
	default:	goto yy83;
	}
yy150:
	YYDEBUG(150, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy151;
	default:	goto yy45;
	}
yy151:
	YYDEBUG(151, *this->reader_);
#line 199 "../re2c/lexer.re"
	{return new Token(TokenType::ElseToken);}
#line 1635 "../src/lexer.cpp"
yy152:
	YYDEBUG(152, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'e':	goto yy161;
	default:	goto yy46;
	}
yy153:
	YYDEBUG(153, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy154;
	default:	goto yy45;
	}
yy154:
	YYDEBUG(154, *this->reader_);
#line 201 "../re2c/lexer.re"
	{return new Token(TokenType::FuncToken);}
#line 1718 "../src/lexer.cpp"
yy155:
	YYDEBUG(155, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy156;
	default:	goto yy45;
	}
yy156:
	YYDEBUG(156, *this->reader_);
#line 192 "../re2c/lexer.re"
	{return new Token(TokenType::NullToken);}
#line 1794 "../src/lexer.cpp"
yy157:
	YYDEBUG(157, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 't':	goto yy163;
	default:	goto yy46;
	}
yy158:
	YYDEBUG(158, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy159;
	default:	goto yy45;
	}
yy159:
	YYDEBUG(159, *this->reader_);
#line 193 "../re2c/lexer.re"
	{return new Token(true);}
#line 1877 "../src/lexer.cpp"
yy160:
	YYDEBUG(160, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 'e':	goto yy165;
	default:	goto yy46;
	}
yy161:
	YYDEBUG(161, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy162;
	default:	goto yy45;
	}
yy162:
	YYDEBUG(162, *this->reader_);
#line 194 "../re2c/lexer.re"
	{return new Token(false);}
#line 1960 "../src/lexer.cpp"
yy163:
	YYDEBUG(163, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy164;
	default:	goto yy45;
	}
yy164:
	YYDEBUG(164, *this->reader_);
#line 202 "../re2c/lexer.re"
	{return new Token(TokenType::PrintToken);}
#line 2036 "../src/lexer.cpp"
yy165:
	YYDEBUG(165, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy166;
	default:	goto yy45;
	}
yy166:
	YYDEBUG(166, *this->reader_);
#line 200 "../re2c/lexer.re"
	{return new Token(TokenType::WhileToken);}
#line 2112 "../src/lexer.cpp"
}
#line 226 "../re2c/lexer.re"

  
  lex_string: {
      std::string str;
      
    lex_string_L1:
      
#line 2122 "../src/lexer.cpp"
{
	char yych;
	unsigned int yyaccept = 0;
	YYDEBUG(167, *this->reader_);
	yych = *this->reader_;
	switch (yych) {
	case 0x00:	goto yy169;
	case '\n':	goto yy173;
	case '"':	goto yy175;
	case '\\':	goto yy177;
	default:	goto yy171;
	}
yy169:
	YYDEBUG(169, *this->reader_);
	++this->reader_;
	YYDEBUG(170, *this->reader_);
#line 234 "../re2c/lexer.re"
	{break;}
#line 2141 "../src/lexer.cpp"
yy171:
	YYDEBUG(171, *this->reader_);
	++this->reader_;
	YYDEBUG(172, *this->reader_);
#line 236 "../re2c/lexer.re"
	{
          str.push_back(yych);
          goto lex_string_L1;
        }
#line 2151 "../src/lexer.cpp"
yy173:
	YYDEBUG(173, *this->reader_);
	++this->reader_;
yy174:
	YYDEBUG(174, *this->reader_);
#line 233 "../re2c/lexer.re"
	{break;}
#line 2159 "../src/lexer.cpp"
yy175:
	YYDEBUG(175, *this->reader_);
	++this->reader_;
	YYDEBUG(176, *this->reader_);
#line 241 "../re2c/lexer.re"
	{
          StringView view(str.c_str(), str.size());
          String* str;
          auto it = this->string_table.find(view);
          if(it == this->string_table.end()){
            str = this->string_table.insert(
              std::make_pair(
                view,
                rc_ptr<String>(make_new<String>(view.first, view.second))
              )
            ).first->second.get();
          }else{
            str = it->second.get();
          }
          return new Token(str);
        }
#line 2181 "../src/lexer.cpp"
yy177:
	YYDEBUG(177, *this->reader_);
	yyaccept = 0;
	yych = *(marker = ++this->reader_);
	switch (yych) {
	case '\n':	goto yy178;
	case '"':	goto yy180;
	case '\'':	goto yy182;
	case '0':
	case '1':
	case '2':
	case '3':	goto yy184;
	case '4':
	case '5':
	case '6':
	case '7':	goto yy186;
	case '?':	goto yy187;
	case 'U':	goto yy189;
	case '\\':	goto yy191;
	case 'a':	goto yy193;
	case 'b':	goto yy195;
	case 'f':	goto yy197;
	case 'n':	goto yy199;
	case 'r':	goto yy201;
	case 't':	goto yy203;
	case 'u':	goto yy205;
	case 'v':	goto yy206;
	case 'x':	goto yy208;
	default:	goto yy174;
	}
yy178:
	YYDEBUG(178, *this->reader_);
	++this->reader_;
	YYDEBUG(179, *this->reader_);
#line 269 "../re2c/lexer.re"
	{goto lex_string_L1;}
#line 2218 "../src/lexer.cpp"
yy180:
	YYDEBUG(180, *this->reader_);
	++this->reader_;
	YYDEBUG(181, *this->reader_);
#line 268 "../re2c/lexer.re"
	{str.push_back('\"'); goto lex_string_L1;}
#line 2225 "../src/lexer.cpp"
yy182:
	YYDEBUG(182, *this->reader_);
	++this->reader_;
	YYDEBUG(183, *this->reader_);
#line 267 "../re2c/lexer.re"
	{str.push_back('\''); goto lex_string_L1;}
#line 2232 "../src/lexer.cpp"
yy184:
	YYDEBUG(184, *this->reader_);
	yyaccept = 1;
	yych = *(marker = ++this->reader_);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy209;
	default:	goto yy185;
	}
yy185:
	YYDEBUG(185, *this->reader_);
#line 271 "../re2c/lexer.re"
	{str.push_back(*(this->reader_ - 1)); goto lex_string_L1;}
#line 2252 "../src/lexer.cpp"
yy186:
	YYDEBUG(186, *this->reader_);
	++this->reader_;
	goto yy185;
yy187:
	YYDEBUG(187, *this->reader_);
	++this->reader_;
	YYDEBUG(188, *this->reader_);
#line 266 "../re2c/lexer.re"
	{str.push_back('\?'); goto lex_string_L1;}
#line 2263 "../src/lexer.cpp"
yy189:
	YYDEBUG(189, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy210;
	default:	goto yy190;
	}
yy190:
	YYDEBUG(190, *this->reader_);
	this->reader_ = marker;
	if (yyaccept == 0) {
		goto yy174;
	} else {
		goto yy185;
	}
yy191:
	YYDEBUG(191, *this->reader_);
	++this->reader_;
	YYDEBUG(192, *this->reader_);
#line 265 "../re2c/lexer.re"
	{str.push_back('\\'); goto lex_string_L1;}
#line 2306 "../src/lexer.cpp"
yy193:
	YYDEBUG(193, *this->reader_);
	++this->reader_;
	YYDEBUG(194, *this->reader_);
#line 258 "../re2c/lexer.re"
	{str.push_back('\a'); goto lex_string_L1;}
#line 2313 "../src/lexer.cpp"
yy195:
	YYDEBUG(195, *this->reader_);
	++this->reader_;
	YYDEBUG(196, *this->reader_);
#line 259 "../re2c/lexer.re"
	{str.push_back('\b'); goto lex_string_L1;}
#line 2320 "../src/lexer.cpp"
yy197:
	YYDEBUG(197, *this->reader_);
	++this->reader_;
	YYDEBUG(198, *this->reader_);
#line 260 "../re2c/lexer.re"
	{str.push_back('\f'); goto lex_string_L1;}
#line 2327 "../src/lexer.cpp"
yy199:
	YYDEBUG(199, *this->reader_);
	++this->reader_;
	YYDEBUG(200, *this->reader_);
#line 261 "../re2c/lexer.re"
	{str.push_back('\n'); goto lex_string_L1;}
#line 2334 "../src/lexer.cpp"
yy201:
	YYDEBUG(201, *this->reader_);
	++this->reader_;
	YYDEBUG(202, *this->reader_);
#line 262 "../re2c/lexer.re"
	{str.push_back('\r'); goto lex_string_L1;}
#line 2341 "../src/lexer.cpp"
yy203:
	YYDEBUG(203, *this->reader_);
	++this->reader_;
	YYDEBUG(204, *this->reader_);
#line 263 "../re2c/lexer.re"
	{str.push_back('\t'); goto lex_string_L1;}
#line 2348 "../src/lexer.cpp"
yy205:
	YYDEBUG(205, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy211;
	default:	goto yy190;
	}
yy206:
	YYDEBUG(206, *this->reader_);
	++this->reader_;
	YYDEBUG(207, *this->reader_);
#line 264 "../re2c/lexer.re"
	{str.push_back('\v'); goto lex_string_L1;}
#line 2383 "../src/lexer.cpp"
yy208:
	YYDEBUG(208, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy212;
	default:	goto yy190;
	}
yy209:
	YYDEBUG(209, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy213;
	default:	goto yy190;
	}
yy210:
	YYDEBUG(210, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy215;
	default:	goto yy190;
	}
yy211:
	YYDEBUG(211, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy216;
	default:	goto yy190;
	}
yy212:
	YYDEBUG(212, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy217;
	default:	goto yy190;
	}
yy213:
	YYDEBUG(213, *this->reader_);
	++this->reader_;
	YYDEBUG(214, *this->reader_);
#line 273 "../re2c/lexer.re"
	{
          str.push_back(
            (*(this->reader_ - 3) * 0x40) |
            (*(this->reader_ - 2) * 0x8) |
            (*this->reader_ - 1)
          );
          goto lex_string_L1;
        }
#line 2523 "../src/lexer.cpp"
yy215:
	YYDEBUG(215, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy219;
	default:	goto yy190;
	}
yy216:
	YYDEBUG(216, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy220;
	default:	goto yy190;
	}
yy217:
	YYDEBUG(217, *this->reader_);
	++this->reader_;
	YYDEBUG(218, *this->reader_);
#line 281 "../re2c/lexer.re"
	{
          str.push_back((*(this->reader_ - 2) * 0x10) | (*this->reader_ - 1));
          goto lex_string_L1;
        }
#line 2589 "../src/lexer.cpp"
yy219:
	YYDEBUG(219, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy221;
	default:	goto yy190;
	}
yy220:
	YYDEBUG(220, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy222;
	default:	goto yy190;
	}
yy221:
	YYDEBUG(221, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy224;
	default:	goto yy190;
	}
yy222:
	YYDEBUG(222, *this->reader_);
	++this->reader_;
	YYDEBUG(223, *this->reader_);
#line 285 "../re2c/lexer.re"
	{
          enterUtf8CodePoint_<4>(&str, this->reader_);
          goto lex_string_L1;
        }
#line 2683 "../src/lexer.cpp"
yy224:
	YYDEBUG(224, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy225;
	default:	goto yy190;
	}
yy225:
	YYDEBUG(225, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy226;
	default:	goto yy190;
	}
yy226:
	YYDEBUG(226, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy227;
	default:	goto yy190;
	}
yy227:
	YYDEBUG(227, *this->reader_);
	++this->reader_;
	YYDEBUG(228, *this->reader_);
#line 289 "../re2c/lexer.re"
	{
          enterUtf8CodePoint_<8>(&str, this->reader_);
          goto lex_string_L1;
        }
#line 2777 "../src/lexer.cpp"
}
#line 293 "../re2c/lexer.re"

    }
    
  lex_block_comment:
    
#line 2785 "../src/lexer.cpp"
{
	char yych;
	YYDEBUG(229, *this->reader_);
	yych = *this->reader_;
	switch (yych) {
	case 0x00:	goto yy231;
	case '*':	goto yy235;
	case '/':	goto yy236;
	default:	goto yy233;
	}
yy231:
	YYDEBUG(231, *this->reader_);
	++this->reader_;
	YYDEBUG(232, *this->reader_);
#line 298 "../re2c/lexer.re"
	{break;}
#line 2802 "../src/lexer.cpp"
yy233:
	YYDEBUG(233, *this->reader_);
	++this->reader_;
yy234:
	YYDEBUG(234, *this->reader_);
#line 299 "../re2c/lexer.re"
	{goto lex_block_comment;}
#line 2810 "../src/lexer.cpp"
yy235:
	YYDEBUG(235, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '/':	goto yy237;
	default:	goto yy234;
	}
yy236:
	YYDEBUG(236, *this->reader_);
	yych = *++this->reader_;
	switch (yych) {
	case '*':	goto yy239;
	default:	goto yy234;
	}
yy237:
	YYDEBUG(237, *this->reader_);
	++this->reader_;
	YYDEBUG(238, *this->reader_);
#line 301 "../re2c/lexer.re"
	{if(--counter) goto lex_block_comment; else continue;}
#line 2831 "../src/lexer.cpp"
yy239:
	YYDEBUG(239, *this->reader_);
	++this->reader_;
	YYDEBUG(240, *this->reader_);
#line 300 "../re2c/lexer.re"
	{++counter; goto lex_block_comment;}
#line 2838 "../src/lexer.cpp"
}
#line 302 "../re2c/lexer.re"

  }
  
  return new Token(TokenType::EndToken);
  
  #undef YYDEBUG
}

void Lexer::setCheckpoint(){
  this->_checkpoints.push_back(this->old_reader_);
}

void Lexer::removeCheckpoint(){
  this->_checkpoints.pop_back();
}

void Lexer::revert(){
  this->reader_ = this->_checkpoints.back();
  this->_checkpoints.pop_back();
}