/* Generated by re2c 1.0.3 on Tue Aug 14 20:59:07 2018 */
#line 1 "../re2c/lexer.re"
#include "lexer.h"

#include <cstdint>

#include <stack>

namespace{
  
  constexpr uint64_t utf8Mask_(int bytes){
    if(bytes >= 2){
      int mask1 = 0x8000, mask2 = 0x80;
      for(; bytes > 2; --bytes){
        mask1 = (mask1 << 8) | (mask1 << 7);
        mask2 = (mask2 << 8) | 0x80;
      }
      return mask1 | mask2;
    }else return 0;
  }
  
  template<int bytes>
  inline uint64_t splitUtf8CodePoint_(uint64_t code_point){
    uint64_t mask = 0x3f;
    for(int i = 1; i < bytes; ++i){
      code_point = (code_point & mask) | ((code_point & ~mask) << 2);
      mask = (mask << 8) | 0xff;
    }
    return code_point;
  }
  
  template<int chars>
  inline void enterUtf8CodePoint_(std::string* dest, const char* code){
    uint64_t code_point;
    code -= chars;
    for(int i = 0; i < chars; ++i){
      code_point <<= 8;
      if(isdigit(*code)){
        code_point |= (*code) - '0';
      }else{
        code_point |= (*code | 0x20) - 'a' + 10;
      }
      ++code;
    }
    if(code_point < 0x80){
      dest->push_back((char)code_point);
      return;
    }else{
      int bytes = 2;
      for(uint64_t cp = code_point >> 11; cp > 0; ++bytes, cp >> 5);
      
      switch(bytes){
      case 2:
        code_point = splitUtf8CodePoint_<2>(code_point) | utf8Mask_(2);
        goto write_2_bytes;
      case 3:
        code_point = splitUtf8CodePoint_<3>(code_point) | utf8Mask_(3);
        goto write_3_bytes;
      case 4:
        code_point = splitUtf8CodePoint_<4>(code_point) | utf8Mask_(4);
        goto write_4_bytes;
      case 5:
        code_point = splitUtf8CodePoint_<5>(code_point) | utf8Mask_(5);
        goto write_5_bytes;
      case 6:
        code_point = splitUtf8CodePoint_<6>(code_point) | utf8Mask_(6);
        goto write_6_bytes;
      case 7:
        code_point = splitUtf8CodePoint_<7>(code_point) | utf8Mask_(7);
        goto write_7_bytes;
      }
      
    write_7_bytes:
      dest->push_back(code[-7]);
    write_6_bytes:
      dest->push_back(code[-6]);
    write_5_bytes:
      dest->push_back(code[-5]);
    write_4_bytes:
      dest->push_back(code[-4]);
    write_3_bytes:
      dest->push_back(code[-3]);
    write_2_bytes:
      dest->push_back(code[-2]);
      dest->push_back(code[-1]);
    }
  }
}

Lexer::Lexer(const char* mem){
  this->mem_ = mem;
}

std::vector<Lexeme> Lexer::lex(std::vector<std::unique_ptr<char[]>>* errors){
  const char* marker;
  const char* token;
  
  const char* reader = this->mem_;
  int counter = 0;
  
  #define YYDEBUG(state, current)
  
  std::vector<Lexeme> lexemes;
  std::stack<char> br_stack;
  br_stack.push('#');
  
  uint16_t line = 1;
  const char* line_start = reader;
  
  #define PLACE_LEXEME(params) \
    lexemes.emplace_back(params, std::make_pair(line, token - line_start));
  #define PUT_LEXEME(params) \
    lexemes.emplace_back(params, std::make_pair(line, token - line_start)); \
    continue;
  
  lexemes.emplace_back(LexemeType::Semicolon, std::make_pair(0, 0));
  
  for(;;){
    token = reader;
    
    #line 125 "../re2c/lexer.re"

    
    
#line 126 "../src/lexer.cpp"
{
	char yych;
	unsigned int yyaccept = 0;
	YYDEBUG(0, *reader);
	yych = *reader;
	switch (yych) {
	case 0x00:	goto yy2;
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case '#':
	case '$':
	case '&':
	case '\'':
	case '?':
	case '@':
	case '\\':
	case '^':
	case '`':
	case '|':
	case '~':
	case 0x7F:	goto yy4;
	case '\t':
	case '\v':
	case '\f':
	case '\r':
	case ' ':	goto yy6;
	case '\n':	goto yy8;
	case '!':	goto yy10;
	case '"':	goto yy11;
	case '%':	goto yy13;
	case '(':	goto yy15;
	case ')':	goto yy17;
	case '*':	goto yy19;
	case '+':	goto yy21;
	case ',':	goto yy23;
	case '-':	goto yy25;
	case '.':	goto yy27;
	case '/':	goto yy28;
	case '0':	goto yy30;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy32;
	case ':':	goto yy34;
	case ';':	goto yy35;
	case '<':	goto yy37;
	case '=':	goto yy39;
	case '>':	goto yy41;
	case '[':	goto yy46;
	case ']':	goto yy48;
	case 'a':	goto yy50;
	case 'd':	goto yy51;
	case 'e':	goto yy52;
	case 'f':	goto yy53;
	case 'i':	goto yy54;
	case 'n':	goto yy55;
	case 'o':	goto yy56;
	case 'p':	goto yy57;
	case 't':	goto yy58;
	case 'w':	goto yy59;
	case '{':	goto yy60;
	case '}':	goto yy62;
	default:	goto yy43;
	}
yy2:
	YYDEBUG(2, *reader);
	++reader;
	YYDEBUG(3, *reader);
#line 128 "../re2c/lexer.re"
	{break;}
#line 226 "../src/lexer.cpp"
yy4:
	YYDEBUG(4, *reader);
	++reader;
yy5:
	YYDEBUG(5, *reader);
#line 130 "../re2c/lexer.re"
	{
        if(lexemes.back().type != LexemeType::Error){
          errors->emplace_back(dynSprintf("line %d: Invalid symbol.", line));
          PUT_LEXEME(LexemeType::Error);
        } else continue;
      }
#line 239 "../src/lexer.cpp"
yy6:
	YYDEBUG(6, *reader);
	++reader;
	YYDEBUG(7, *reader);
#line 138 "../re2c/lexer.re"
	{continue;}
#line 246 "../src/lexer.cpp"
yy8:
	YYDEBUG(8, *reader);
	++reader;
	YYDEBUG(9, *reader);
#line 140 "../re2c/lexer.re"
	{
        if((br_stack.top() == '{'
        || br_stack.top() == '#')
        && isStopLexeme(lexemes.back())){
          PLACE_LEXEME(LexemeType::Newline);
        }
        ++line;
        line_start = reader;
        continue;
      }
#line 262 "../src/lexer.cpp"
yy10:
	YYDEBUG(10, *reader);
	yych = *++reader;
	switch (yych) {
	case '=':	goto yy64;
	default:	goto yy5;
	}
yy11:
	YYDEBUG(11, *reader);
	++reader;
	YYDEBUG(12, *reader);
#line 172 "../re2c/lexer.re"
	{
        goto lex_string;
      }
#line 278 "../src/lexer.cpp"
yy13:
	YYDEBUG(13, *reader);
	yych = *++reader;
	switch (yych) {
	case '=':	goto yy66;
	default:	goto yy14;
	}
yy14:
	YYDEBUG(14, *reader);
#line 182 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Mod)}
#line 290 "../src/lexer.cpp"
yy15:
	YYDEBUG(15, *reader);
	++reader;
	YYDEBUG(16, *reader);
#line 203 "../re2c/lexer.re"
	{
        br_stack.push('(');
        PUT_LEXEME(LexemeType::LParen)
      }
#line 300 "../src/lexer.cpp"
yy17:
	YYDEBUG(17, *reader);
	++reader;
	YYDEBUG(18, *reader);
#line 215 "../re2c/lexer.re"
	{
        if(br_stack.top() == '('){
          br_stack.pop();
          PUT_LEXEME(LexemeType::RParen)
        }else{
          errors->emplace_back(dynSprintf("line %d: Unexpected ')'.", line));
          PUT_LEXEME(LexemeType::Error);
        }
      }
#line 315 "../src/lexer.cpp"
yy19:
	YYDEBUG(19, *reader);
	yych = *++reader;
	switch (yych) {
	case '=':	goto yy68;
	default:	goto yy20;
	}
yy20:
	YYDEBUG(20, *reader);
#line 180 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Mul)}
#line 327 "../src/lexer.cpp"
yy21:
	YYDEBUG(21, *reader);
	yych = *++reader;
	switch (yych) {
	case '+':	goto yy70;
	case '=':	goto yy72;
	default:	goto yy22;
	}
yy22:
	YYDEBUG(22, *reader);
#line 178 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Plus)}
#line 340 "../src/lexer.cpp"
yy23:
	YYDEBUG(23, *reader);
	++reader;
	YYDEBUG(24, *reader);
#line 199 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Comma)}
#line 347 "../src/lexer.cpp"
yy25:
	YYDEBUG(25, *reader);
	yych = *++reader;
	switch (yych) {
	case '=':	goto yy74;
	default:	goto yy26;
	}
yy26:
	YYDEBUG(26, *reader);
#line 179 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Minus)}
#line 359 "../src/lexer.cpp"
yy27:
	YYDEBUG(27, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy76;
	default:	goto yy5;
	}
yy28:
	YYDEBUG(28, *reader);
	yych = *++reader;
	switch (yych) {
	case '*':	goto yy79;
	case '/':	goto yy81;
	case '=':	goto yy84;
	default:	goto yy29;
	}
yy29:
	YYDEBUG(29, *reader);
#line 181 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Div)}
#line 389 "../src/lexer.cpp"
yy30:
	YYDEBUG(30, *reader);
	yyaccept = 0;
	yych = *(marker = ++reader);
	switch (yych) {
	case 'B':
	case 'b':	goto yy86;
	case 'O':
	case 'o':	goto yy89;
	case 'X':
	case 'x':	goto yy90;
	default:	goto yy33;
	}
yy31:
	YYDEBUG(31, *reader);
#line 156 "../re2c/lexer.re"
	{PUT_LEXEME(strtoull(token, nullptr, 10))}
#line 407 "../src/lexer.cpp"
yy32:
	YYDEBUG(32, *reader);
	yych = *++reader;
yy33:
	YYDEBUG(33, *reader);
	switch (yych) {
	case '.':	goto yy76;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy32;
	case 'E':
	case 'e':	goto yy88;
	default:	goto yy31;
	}
yy34:
	YYDEBUG(34, *reader);
	yych = *++reader;
	switch (yych) {
	case '=':	goto yy91;
	default:	goto yy5;
	}
yy35:
	YYDEBUG(35, *reader);
	++reader;
	YYDEBUG(36, *reader);
#line 201 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Semicolon)}
#line 442 "../src/lexer.cpp"
yy37:
	YYDEBUG(37, *reader);
	yych = *++reader;
	switch (yych) {
	case '=':	goto yy93;
	default:	goto yy38;
	}
yy38:
	YYDEBUG(38, *reader);
#line 195 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Lt)}
#line 454 "../src/lexer.cpp"
yy39:
	YYDEBUG(39, *reader);
	yych = *++reader;
	switch (yych) {
	case '=':	goto yy95;
	default:	goto yy40;
	}
yy40:
	YYDEBUG(40, *reader);
#line 185 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Assign)}
#line 466 "../src/lexer.cpp"
yy41:
	YYDEBUG(41, *reader);
	yych = *++reader;
	switch (yych) {
	case '=':	goto yy97;
	default:	goto yy42;
	}
yy42:
	YYDEBUG(42, *reader);
#line 194 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Gt)}
#line 478 "../src/lexer.cpp"
yy43:
	YYDEBUG(43, *reader);
	yych = *++reader;
yy44:
	YYDEBUG(44, *reader);
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy45;
	default:	goto yy43;
	}
yy45:
	YYDEBUG(45, *reader);
#line 278 "../re2c/lexer.re"
	{
        StringView view(token, reader);
        String* str;
        auto it = this->string_table.find(view);
        if(it == this->string_table.end()){
          str = this->string_table.insert(
            std::make_pair(
              view,
              rc_ptr<String>(make_new<String>(view.first, view.second))
            )
          ).first->second.get();
        }else{
          str = it->second.get();
        }
        lexemes.emplace_back(
          LexemeType::Identifier,
          str,
          std::make_pair(line, token - line_start)
        );
        
        continue;
      }
#line 577 "../src/lexer.cpp"
yy46:
	YYDEBUG(46, *reader);
	++reader;
	YYDEBUG(47, *reader);
#line 211 "../re2c/lexer.re"
	{
        br_stack.push('[');
        PUT_LEXEME(LexemeType::LBracket)
      }
#line 587 "../src/lexer.cpp"
yy48:
	YYDEBUG(48, *reader);
	++reader;
	YYDEBUG(49, *reader);
#line 236 "../re2c/lexer.re"
	{
        if(br_stack.top() == '['){
          br_stack.pop();
          PUT_LEXEME(LexemeType::RBracket)
        }else{
          errors->emplace_back(dynSprintf("line %d: Unexpected ']'.", line));
          PUT_LEXEME(LexemeType::Error);
        }
      }
#line 602 "../src/lexer.cpp"
yy50:
	YYDEBUG(50, *reader);
	yych = *++reader;
	switch (yych) {
	case 'n':	goto yy99;
	case 's':	goto yy100;
	default:	goto yy44;
	}
yy51:
	YYDEBUG(51, *reader);
	yych = *++reader;
	switch (yych) {
	case 'o':	goto yy101;
	default:	goto yy44;
	}
yy52:
	YYDEBUG(52, *reader);
	yych = *++reader;
	switch (yych) {
	case 'l':	goto yy103;
	default:	goto yy44;
	}
yy53:
	YYDEBUG(53, *reader);
	yych = *++reader;
	switch (yych) {
	case 'a':	goto yy104;
	case 'u':	goto yy105;
	default:	goto yy44;
	}
yy54:
	YYDEBUG(54, *reader);
	yych = *++reader;
	switch (yych) {
	case 'f':	goto yy106;
	default:	goto yy44;
	}
yy55:
	YYDEBUG(55, *reader);
	yych = *++reader;
	switch (yych) {
	case 'o':	goto yy108;
	case 'u':	goto yy109;
	default:	goto yy44;
	}
yy56:
	YYDEBUG(56, *reader);
	yych = *++reader;
	switch (yych) {
	case 'r':	goto yy110;
	default:	goto yy44;
	}
yy57:
	YYDEBUG(57, *reader);
	yych = *++reader;
	switch (yych) {
	case 'r':	goto yy112;
	default:	goto yy44;
	}
yy58:
	YYDEBUG(58, *reader);
	yych = *++reader;
	switch (yych) {
	case 'r':	goto yy113;
	default:	goto yy44;
	}
yy59:
	YYDEBUG(59, *reader);
	yych = *++reader;
	switch (yych) {
	case 'h':	goto yy114;
	default:	goto yy44;
	}
yy60:
	YYDEBUG(60, *reader);
	++reader;
	YYDEBUG(61, *reader);
#line 207 "../re2c/lexer.re"
	{
        br_stack.push('{');
        PUT_LEXEME(LexemeType::LBrace)
      }
#line 685 "../src/lexer.cpp"
yy62:
	YYDEBUG(62, *reader);
	++reader;
	YYDEBUG(63, *reader);
#line 224 "../re2c/lexer.re"
	{
        if(br_stack.top() == '{'){
          br_stack.pop();
          if(lexemes.back().type == LexemeType::Newline){
            lexemes.pop_back();
          }
          PUT_LEXEME(LexemeType::RBrace)
        }else{
          errors->emplace_back(dynSprintf("line %d: Unexpected '}'.", line));
          PUT_LEXEME(LexemeType::Error);
        }
      }
#line 703 "../src/lexer.cpp"
yy64:
	YYDEBUG(64, *reader);
	++reader;
	YYDEBUG(65, *reader);
#line 193 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Neq)}
#line 710 "../src/lexer.cpp"
yy66:
	YYDEBUG(66, *reader);
	++reader;
	YYDEBUG(67, *reader);
#line 190 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::ModAssign)}
#line 717 "../src/lexer.cpp"
yy68:
	YYDEBUG(68, *reader);
	++reader;
	YYDEBUG(69, *reader);
#line 188 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::MulAssign)}
#line 724 "../src/lexer.cpp"
yy70:
	YYDEBUG(70, *reader);
	yych = *++reader;
	switch (yych) {
	case '=':	goto yy115;
	default:	goto yy71;
	}
yy71:
	YYDEBUG(71, *reader);
#line 183 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Append)}
#line 736 "../src/lexer.cpp"
yy72:
	YYDEBUG(72, *reader);
	++reader;
	YYDEBUG(73, *reader);
#line 186 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::AddAssign)}
#line 743 "../src/lexer.cpp"
yy74:
	YYDEBUG(74, *reader);
	++reader;
	YYDEBUG(75, *reader);
#line 187 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::SubAssign)}
#line 750 "../src/lexer.cpp"
yy76:
	YYDEBUG(76, *reader);
	yych = *++reader;
	YYDEBUG(77, *reader);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy76;
	case 'E':
	case 'e':	goto yy88;
	default:	goto yy78;
	}
yy78:
	YYDEBUG(78, *reader);
#line 169 "../re2c/lexer.re"
	{PUT_LEXEME(atof(token))}
#line 774 "../src/lexer.cpp"
yy79:
	YYDEBUG(79, *reader);
	++reader;
	YYDEBUG(80, *reader);
#line 153 "../re2c/lexer.re"
	{counter = 1; goto lex_block_comment;}
#line 781 "../src/lexer.cpp"
yy81:
	YYDEBUG(81, *reader);
	yych = *++reader;
	YYDEBUG(82, *reader);
	switch (yych) {
	case 0x00:
	case '\n':	goto yy83;
	default:	goto yy81;
	}
yy83:
	YYDEBUG(83, *reader);
#line 152 "../re2c/lexer.re"
	{continue;}
#line 795 "../src/lexer.cpp"
yy84:
	YYDEBUG(84, *reader);
	++reader;
	YYDEBUG(85, *reader);
#line 189 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::DivAssign)}
#line 802 "../src/lexer.cpp"
yy86:
	YYDEBUG(86, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':	goto yy117;
	default:	goto yy87;
	}
yy87:
	YYDEBUG(87, *reader);
	reader = marker;
	if (yyaccept == 0) {
		goto yy31;
	} else {
		goto yy78;
	}
yy88:
	YYDEBUG(88, *reader);
	yyaccept = 1;
	yych = *(marker = ++reader);
	switch (yych) {
	case '+':
	case '-':	goto yy120;
	default:	goto yy122;
	}
yy89:
	YYDEBUG(89, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy123;
	default:	goto yy87;
	}
yy90:
	YYDEBUG(90, *reader);
	yych = *++reader;
	switch (yych) {
	case '.':	goto yy126;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy127;
	default:	goto yy87;
	}
yy91:
	YYDEBUG(91, *reader);
	++reader;
	YYDEBUG(92, *reader);
#line 184 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Define)}
#line 877 "../src/lexer.cpp"
yy93:
	YYDEBUG(93, *reader);
	yych = *++reader;
	switch (yych) {
	case '>':	goto yy130;
	default:	goto yy94;
	}
yy94:
	YYDEBUG(94, *reader);
#line 197 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Leq)}
#line 889 "../src/lexer.cpp"
yy95:
	YYDEBUG(95, *reader);
	++reader;
	YYDEBUG(96, *reader);
#line 192 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Eq)}
#line 896 "../src/lexer.cpp"
yy97:
	YYDEBUG(97, *reader);
	++reader;
	YYDEBUG(98, *reader);
#line 196 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Geq)}
#line 903 "../src/lexer.cpp"
yy99:
	YYDEBUG(99, *reader);
	yych = *++reader;
	switch (yych) {
	case 'd':	goto yy132;
	default:	goto yy44;
	}
yy100:
	YYDEBUG(100, *reader);
	yych = *++reader;
	switch (yych) {
	case 's':	goto yy134;
	default:	goto yy44;
	}
yy101:
	YYDEBUG(101, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy102;
	default:	goto yy43;
	}
yy102:
	YYDEBUG(102, *reader);
#line 253 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Do)}
#line 993 "../src/lexer.cpp"
yy103:
	YYDEBUG(103, *reader);
	yych = *++reader;
	switch (yych) {
	case 's':	goto yy135;
	default:	goto yy44;
	}
yy104:
	YYDEBUG(104, *reader);
	yych = *++reader;
	switch (yych) {
	case 'l':	goto yy136;
	default:	goto yy44;
	}
yy105:
	YYDEBUG(105, *reader);
	yych = *++reader;
	switch (yych) {
	case 'n':	goto yy137;
	default:	goto yy44;
	}
yy106:
	YYDEBUG(106, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy107;
	default:	goto yy43;
	}
yy107:
	YYDEBUG(107, *reader);
#line 251 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::If)}
#line 1090 "../src/lexer.cpp"
yy108:
	YYDEBUG(108, *reader);
	yych = *++reader;
	switch (yych) {
	case 't':	goto yy138;
	default:	goto yy44;
	}
yy109:
	YYDEBUG(109, *reader);
	yych = *++reader;
	switch (yych) {
	case 'l':	goto yy140;
	default:	goto yy44;
	}
yy110:
	YYDEBUG(110, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy111;
	default:	goto yy43;
	}
yy111:
	YYDEBUG(111, *reader);
#line 264 "../re2c/lexer.re"
	{
        if(lexemes.back().type == LexemeType::Newline){
          lexemes.pop_back();
        }
        PUT_LEXEME(LexemeType::Or)
      }
#line 1185 "../src/lexer.cpp"
yy112:
	YYDEBUG(112, *reader);
	yych = *++reader;
	switch (yych) {
	case 'i':	goto yy141;
	default:	goto yy44;
	}
yy113:
	YYDEBUG(113, *reader);
	yych = *++reader;
	switch (yych) {
	case 'u':	goto yy142;
	default:	goto yy44;
	}
yy114:
	YYDEBUG(114, *reader);
	yych = *++reader;
	switch (yych) {
	case 'i':	goto yy143;
	default:	goto yy44;
	}
yy115:
	YYDEBUG(115, *reader);
	++reader;
	YYDEBUG(116, *reader);
#line 191 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::AppendAssign)}
#line 1213 "../src/lexer.cpp"
yy117:
	YYDEBUG(117, *reader);
	yych = *++reader;
	YYDEBUG(118, *reader);
	switch (yych) {
	case '0':
	case '1':	goto yy117;
	default:	goto yy119;
	}
yy119:
	YYDEBUG(119, *reader);
#line 157 "../re2c/lexer.re"
	{PUT_LEXEME(strtoull(token + 2, nullptr, 2))}
#line 1227 "../src/lexer.cpp"
yy120:
	YYDEBUG(120, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy121;
	default:	goto yy87;
	}
yy121:
	YYDEBUG(121, *reader);
	yych = *++reader;
yy122:
	YYDEBUG(122, *reader);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy121;
	default:	goto yy78;
	}
yy123:
	YYDEBUG(123, *reader);
	yych = *++reader;
	YYDEBUG(124, *reader);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy123;
	default:	goto yy125;
	}
yy125:
	YYDEBUG(125, *reader);
#line 158 "../re2c/lexer.re"
	{PUT_LEXEME(strtoull(token + 2, nullptr, 8))}
#line 1281 "../src/lexer.cpp"
yy126:
	YYDEBUG(126, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy144;
	default:	goto yy87;
	}
yy127:
	YYDEBUG(127, *reader);
	yych = *++reader;
	YYDEBUG(128, *reader);
	switch (yych) {
	case '.':	goto yy144;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy127;
	case 'P':
	case 'p':	goto yy88;
	default:	goto yy129;
	}
yy129:
	YYDEBUG(129, *reader);
#line 159 "../re2c/lexer.re"
	{PUT_LEXEME(strtoull(token + 2, nullptr, 16))}
#line 1346 "../src/lexer.cpp"
yy130:
	YYDEBUG(130, *reader);
	++reader;
	YYDEBUG(131, *reader);
#line 198 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Cmp)}
#line 1353 "../src/lexer.cpp"
yy132:
	YYDEBUG(132, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy133;
	default:	goto yy43;
	}
yy133:
	YYDEBUG(133, *reader);
#line 258 "../re2c/lexer.re"
	{
        if(lexemes.back().type == LexemeType::Newline){
          lexemes.pop_back();
        }
        PUT_LEXEME(LexemeType::And)
      }
#line 1434 "../src/lexer.cpp"
yy134:
	YYDEBUG(134, *reader);
	yych = *++reader;
	switch (yych) {
	case 'e':	goto yy146;
	default:	goto yy44;
	}
yy135:
	YYDEBUG(135, *reader);
	yych = *++reader;
	switch (yych) {
	case 'e':	goto yy147;
	default:	goto yy44;
	}
yy136:
	YYDEBUG(136, *reader);
	yych = *++reader;
	switch (yych) {
	case 's':	goto yy149;
	default:	goto yy44;
	}
yy137:
	YYDEBUG(137, *reader);
	yych = *++reader;
	switch (yych) {
	case 'c':	goto yy150;
	default:	goto yy44;
	}
yy138:
	YYDEBUG(138, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy139;
	default:	goto yy43;
	}
yy139:
	YYDEBUG(139, *reader);
#line 250 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Not)}
#line 1538 "../src/lexer.cpp"
yy140:
	YYDEBUG(140, *reader);
	yych = *++reader;
	switch (yych) {
	case 'l':	goto yy152;
	default:	goto yy44;
	}
yy141:
	YYDEBUG(141, *reader);
	yych = *++reader;
	switch (yych) {
	case 'n':	goto yy154;
	default:	goto yy44;
	}
yy142:
	YYDEBUG(142, *reader);
	yych = *++reader;
	switch (yych) {
	case 'e':	goto yy155;
	default:	goto yy44;
	}
yy143:
	YYDEBUG(143, *reader);
	yych = *++reader;
	switch (yych) {
	case 'l':	goto yy157;
	default:	goto yy44;
	}
yy144:
	YYDEBUG(144, *reader);
	yych = *++reader;
	YYDEBUG(145, *reader);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy144;
	case 'P':
	case 'p':	goto yy88;
	default:	goto yy78;
	}
yy146:
	YYDEBUG(146, *reader);
	yych = *++reader;
	switch (yych) {
	case 'r':	goto yy158;
	default:	goto yy44;
	}
yy147:
	YYDEBUG(147, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy148;
	default:	goto yy43;
	}
yy148:
	YYDEBUG(148, *reader);
#line 270 "../re2c/lexer.re"
	{
        if(lexemes.back().type == LexemeType::Newline){
          lexemes.pop_back();
        }
        PUT_LEXEME(LexemeType::Else)
      }
#line 1685 "../src/lexer.cpp"
yy149:
	YYDEBUG(149, *reader);
	yych = *++reader;
	switch (yych) {
	case 'e':	goto yy159;
	default:	goto yy44;
	}
yy150:
	YYDEBUG(150, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy151;
	default:	goto yy43;
	}
yy151:
	YYDEBUG(151, *reader);
#line 254 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Func)}
#line 1768 "../src/lexer.cpp"
yy152:
	YYDEBUG(152, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy153;
	default:	goto yy43;
	}
yy153:
	YYDEBUG(153, *reader);
#line 247 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Null)}
#line 1844 "../src/lexer.cpp"
yy154:
	YYDEBUG(154, *reader);
	yych = *++reader;
	switch (yych) {
	case 't':	goto yy161;
	default:	goto yy44;
	}
yy155:
	YYDEBUG(155, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy156;
	default:	goto yy43;
	}
yy156:
	YYDEBUG(156, *reader);
#line 248 "../re2c/lexer.re"
	{PUT_LEXEME(true)}
#line 1927 "../src/lexer.cpp"
yy157:
	YYDEBUG(157, *reader);
	yych = *++reader;
	switch (yych) {
	case 'e':	goto yy163;
	default:	goto yy44;
	}
yy158:
	YYDEBUG(158, *reader);
	yych = *++reader;
	switch (yych) {
	case 't':	goto yy165;
	default:	goto yy44;
	}
yy159:
	YYDEBUG(159, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy160;
	default:	goto yy43;
	}
yy160:
	YYDEBUG(160, *reader);
#line 249 "../re2c/lexer.re"
	{PUT_LEXEME(false)}
#line 2017 "../src/lexer.cpp"
yy161:
	YYDEBUG(161, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy162;
	default:	goto yy43;
	}
yy162:
	YYDEBUG(162, *reader);
#line 255 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Print)}
#line 2093 "../src/lexer.cpp"
yy163:
	YYDEBUG(163, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy164;
	default:	goto yy43;
	}
yy164:
	YYDEBUG(164, *reader);
#line 252 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::For)}
#line 2169 "../src/lexer.cpp"
yy165:
	YYDEBUG(165, *reader);
	yych = *++reader;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case 0x08:
	case '\t':
	case '\n':
	case '\v':
	case '\f':
	case '\r':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '"':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '`':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy166;
	default:	goto yy43;
	}
yy166:
	YYDEBUG(166, *reader);
#line 256 "../re2c/lexer.re"
	{PUT_LEXEME(LexemeType::Assert)}
#line 2245 "../src/lexer.cpp"
}
#line 305 "../re2c/lexer.re"

  
  lex_string: {
      std::string str;
      
    lex_string_L1:
      
#line 2255 "../src/lexer.cpp"
{
	char yych;
	unsigned int yyaccept = 0;
	YYDEBUG(167, *reader);
	yych = *reader;
	switch (yych) {
	case 0x00:	goto yy169;
	case '\n':	goto yy173;
	case '"':	goto yy175;
	case '\\':	goto yy177;
	default:	goto yy171;
	}
yy169:
	YYDEBUG(169, *reader);
	++reader;
	YYDEBUG(170, *reader);
#line 313 "../re2c/lexer.re"
	{break;}
#line 2274 "../src/lexer.cpp"
yy171:
	YYDEBUG(171, *reader);
	++reader;
	YYDEBUG(172, *reader);
#line 315 "../re2c/lexer.re"
	{
          str.push_back(yych);
          goto lex_string_L1;
        }
#line 2284 "../src/lexer.cpp"
yy173:
	YYDEBUG(173, *reader);
	++reader;
yy174:
	YYDEBUG(174, *reader);
#line 312 "../re2c/lexer.re"
	{break;}
#line 2292 "../src/lexer.cpp"
yy175:
	YYDEBUG(175, *reader);
	++reader;
	YYDEBUG(176, *reader);
#line 320 "../re2c/lexer.re"
	{
          StringView view(str.c_str(), str.size());
          String* str;
          auto it = this->string_table.find(view);
          if(it == this->string_table.end()){
            str = this->string_table.insert(
              std::make_pair(
                view,
                rc_ptr<String>(make_new<String>(view.first, view.second))
              )
            ).first->second.get();
          }else{
            str = it->second.get();
          }
          PLACE_LEXEME(str);
          continue;
        }
#line 2315 "../src/lexer.cpp"
yy177:
	YYDEBUG(177, *reader);
	yyaccept = 0;
	yych = *(marker = ++reader);
	switch (yych) {
	case '\n':	goto yy178;
	case '"':	goto yy180;
	case '\'':	goto yy182;
	case '0':
	case '1':
	case '2':
	case '3':	goto yy184;
	case '4':
	case '5':
	case '6':
	case '7':	goto yy186;
	case '?':	goto yy187;
	case 'U':	goto yy189;
	case '\\':	goto yy191;
	case 'a':	goto yy193;
	case 'b':	goto yy195;
	case 'f':	goto yy197;
	case 'n':	goto yy199;
	case 'r':	goto yy201;
	case 't':	goto yy203;
	case 'u':	goto yy205;
	case 'v':	goto yy206;
	case 'x':	goto yy208;
	default:	goto yy174;
	}
yy178:
	YYDEBUG(178, *reader);
	++reader;
	YYDEBUG(179, *reader);
#line 349 "../re2c/lexer.re"
	{goto lex_string_L1;}
#line 2352 "../src/lexer.cpp"
yy180:
	YYDEBUG(180, *reader);
	++reader;
	YYDEBUG(181, *reader);
#line 348 "../re2c/lexer.re"
	{str.push_back('\"'); goto lex_string_L1;}
#line 2359 "../src/lexer.cpp"
yy182:
	YYDEBUG(182, *reader);
	++reader;
	YYDEBUG(183, *reader);
#line 347 "../re2c/lexer.re"
	{str.push_back('\''); goto lex_string_L1;}
#line 2366 "../src/lexer.cpp"
yy184:
	YYDEBUG(184, *reader);
	yyaccept = 1;
	yych = *(marker = ++reader);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy209;
	default:	goto yy185;
	}
yy185:
	YYDEBUG(185, *reader);
#line 351 "../re2c/lexer.re"
	{str.push_back(*(reader - 1)); goto lex_string_L1;}
#line 2386 "../src/lexer.cpp"
yy186:
	YYDEBUG(186, *reader);
	++reader;
	goto yy185;
yy187:
	YYDEBUG(187, *reader);
	++reader;
	YYDEBUG(188, *reader);
#line 346 "../re2c/lexer.re"
	{str.push_back('\?'); goto lex_string_L1;}
#line 2397 "../src/lexer.cpp"
yy189:
	YYDEBUG(189, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy210;
	default:	goto yy190;
	}
yy190:
	YYDEBUG(190, *reader);
	reader = marker;
	if (yyaccept == 0) {
		goto yy174;
	} else {
		goto yy185;
	}
yy191:
	YYDEBUG(191, *reader);
	++reader;
	YYDEBUG(192, *reader);
#line 345 "../re2c/lexer.re"
	{str.push_back('\\'); goto lex_string_L1;}
#line 2440 "../src/lexer.cpp"
yy193:
	YYDEBUG(193, *reader);
	++reader;
	YYDEBUG(194, *reader);
#line 338 "../re2c/lexer.re"
	{str.push_back('\a'); goto lex_string_L1;}
#line 2447 "../src/lexer.cpp"
yy195:
	YYDEBUG(195, *reader);
	++reader;
	YYDEBUG(196, *reader);
#line 339 "../re2c/lexer.re"
	{str.push_back('\b'); goto lex_string_L1;}
#line 2454 "../src/lexer.cpp"
yy197:
	YYDEBUG(197, *reader);
	++reader;
	YYDEBUG(198, *reader);
#line 340 "../re2c/lexer.re"
	{str.push_back('\f'); goto lex_string_L1;}
#line 2461 "../src/lexer.cpp"
yy199:
	YYDEBUG(199, *reader);
	++reader;
	YYDEBUG(200, *reader);
#line 341 "../re2c/lexer.re"
	{str.push_back('\n'); goto lex_string_L1;}
#line 2468 "../src/lexer.cpp"
yy201:
	YYDEBUG(201, *reader);
	++reader;
	YYDEBUG(202, *reader);
#line 342 "../re2c/lexer.re"
	{str.push_back('\r'); goto lex_string_L1;}
#line 2475 "../src/lexer.cpp"
yy203:
	YYDEBUG(203, *reader);
	++reader;
	YYDEBUG(204, *reader);
#line 343 "../re2c/lexer.re"
	{str.push_back('\t'); goto lex_string_L1;}
#line 2482 "../src/lexer.cpp"
yy205:
	YYDEBUG(205, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy211;
	default:	goto yy190;
	}
yy206:
	YYDEBUG(206, *reader);
	++reader;
	YYDEBUG(207, *reader);
#line 344 "../re2c/lexer.re"
	{str.push_back('\v'); goto lex_string_L1;}
#line 2517 "../src/lexer.cpp"
yy208:
	YYDEBUG(208, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy212;
	default:	goto yy190;
	}
yy209:
	YYDEBUG(209, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy213;
	default:	goto yy190;
	}
yy210:
	YYDEBUG(210, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy215;
	default:	goto yy190;
	}
yy211:
	YYDEBUG(211, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy216;
	default:	goto yy190;
	}
yy212:
	YYDEBUG(212, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy217;
	default:	goto yy190;
	}
yy213:
	YYDEBUG(213, *reader);
	++reader;
	YYDEBUG(214, *reader);
#line 353 "../re2c/lexer.re"
	{
          str.push_back(
            (*(reader - 3) * 0x40) |
            (*(reader - 2) * 0x8) |
            (*reader - 1)
          );
          goto lex_string_L1;
        }
#line 2657 "../src/lexer.cpp"
yy215:
	YYDEBUG(215, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy219;
	default:	goto yy190;
	}
yy216:
	YYDEBUG(216, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy220;
	default:	goto yy190;
	}
yy217:
	YYDEBUG(217, *reader);
	++reader;
	YYDEBUG(218, *reader);
#line 361 "../re2c/lexer.re"
	{
          str.push_back((*(reader - 2) * 0x10) | (*reader - 1));
          goto lex_string_L1;
        }
#line 2723 "../src/lexer.cpp"
yy219:
	YYDEBUG(219, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy221;
	default:	goto yy190;
	}
yy220:
	YYDEBUG(220, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy222;
	default:	goto yy190;
	}
yy221:
	YYDEBUG(221, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy224;
	default:	goto yy190;
	}
yy222:
	YYDEBUG(222, *reader);
	++reader;
	YYDEBUG(223, *reader);
#line 365 "../re2c/lexer.re"
	{
          enterUtf8CodePoint_<4>(&str, reader);
          goto lex_string_L1;
        }
#line 2817 "../src/lexer.cpp"
yy224:
	YYDEBUG(224, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy225;
	default:	goto yy190;
	}
yy225:
	YYDEBUG(225, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy226;
	default:	goto yy190;
	}
yy226:
	YYDEBUG(226, *reader);
	yych = *++reader;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy227;
	default:	goto yy190;
	}
yy227:
	YYDEBUG(227, *reader);
	++reader;
	YYDEBUG(228, *reader);
#line 369 "../re2c/lexer.re"
	{
          enterUtf8CodePoint_<8>(&str, reader);
          goto lex_string_L1;
        }
#line 2911 "../src/lexer.cpp"
}
#line 373 "../re2c/lexer.re"

    }
    
  lex_block_comment:
    
#line 2919 "../src/lexer.cpp"
{
	char yych;
	YYDEBUG(229, *reader);
	yych = *reader;
	switch (yych) {
	case 0x00:	goto yy231;
	case '\n':	goto yy235;
	case '*':	goto yy237;
	case '/':	goto yy238;
	default:	goto yy233;
	}
yy231:
	YYDEBUG(231, *reader);
	++reader;
	YYDEBUG(232, *reader);
#line 378 "../re2c/lexer.re"
	{break;}
#line 2937 "../src/lexer.cpp"
yy233:
	YYDEBUG(233, *reader);
	++reader;
yy234:
	YYDEBUG(234, *reader);
#line 379 "../re2c/lexer.re"
	{goto lex_block_comment;}
#line 2945 "../src/lexer.cpp"
yy235:
	YYDEBUG(235, *reader);
	++reader;
	YYDEBUG(236, *reader);
#line 382 "../re2c/lexer.re"
	{
        ++line;
        line_start = reader;
        if((br_stack.top() == '{'
        || br_stack.top() == '#')
        && isStopLexeme(lexemes.back())){
          PLACE_LEXEME(LexemeType::Newline);
        }
        goto lex_block_comment;
      }
#line 2961 "../src/lexer.cpp"
yy237:
	YYDEBUG(237, *reader);
	yych = *++reader;
	switch (yych) {
	case '/':	goto yy239;
	default:	goto yy234;
	}
yy238:
	YYDEBUG(238, *reader);
	yych = *++reader;
	switch (yych) {
	case '*':	goto yy241;
	default:	goto yy234;
	}
yy239:
	YYDEBUG(239, *reader);
	++reader;
	YYDEBUG(240, *reader);
#line 381 "../re2c/lexer.re"
	{if(--counter) goto lex_block_comment; else continue;}
#line 2982 "../src/lexer.cpp"
yy241:
	YYDEBUG(241, *reader);
	++reader;
	YYDEBUG(242, *reader);
#line 380 "../re2c/lexer.re"
	{++counter; goto lex_block_comment;}
#line 2989 "../src/lexer.cpp"
}
#line 392 "../re2c/lexer.re"

  }
  
  lexemes.emplace_back(LexemeType::End, std::make_pair(line, reader - line_start));
  
  #undef PLACE_LEXEME
  #undef PUT_LEXEME
  
  return lexemes;
}
